// Background bug reports for HUB ONE, most of them in CRM. Same shape as templates.ts.

import type { BugTemplate } from "./templates";

const crm = (feature: string) => ({ project: "hub" as const, module: "crm", feature });
const mod = (module: string, feature: string) => ({ project: "hub" as const, module, feature });

export const HUB_TEMPLATES: BugTemplate[] = [
  // ------------------------------------------------------------------ HUB ONE · CRM
  {
    id: "crm-contact-phone-format",
    ...crm("Contacts"),
    title: "Phone numbers with a country code lose the '+' when saved",
    description: "Saving a contact with an international phone number drops the leading plus sign.",
    steps: ["Open CRM › Contacts › New contact", "Enter phone +880 1711 223344", "Save and reopen the contact"],
    expected: "The phone number is saved as +880 1711 223344.",
    actual: "The phone number is shown as 880 1711 223344, and click-to-call dials the wrong number.",
    severity: "major", tags: ["phone"], frequency: "always",
    fix: "Phone numbers are stored in E.164 format and the '+' is kept.", rootCause: "backend",
  },
  {
    id: "crm-contact-merge-activities",
    ...crm("Contacts"),
    title: "Merging two contacts drops the activities of the second contact",
    description: "After merging duplicate contacts, calls and emails logged on the merged-away contact are gone.",
    steps: ["Open CRM › Contacts and select two duplicates of Karim Ahmed", "Click Merge and keep the first record", "Open the merged contact's timeline"],
    expected: "The timeline shows the activities of both contacts.",
    actual: "Only the first contact's activities are shown; 12 calls from the second contact are missing.",
    severity: "critical", priority: "high", tags: ["merge", "data-integrity"], frequency: "always",
    fix: "Merging now moves activities, notes and files to the kept contact.", rootCause: "backend",
  },
  {
    id: "crm-contact-search-email",
    ...crm("Contacts"),
    title: "Contact search doesn't find people by email domain",
    description: "Searching for '@deltatraders.com' returns no contacts although several have that domain.",
    steps: ["Open CRM › Contacts", "Type '@deltatraders.com' in the search box"],
    expected: "All contacts with a deltatraders.com email are listed.",
    actual: "'No contacts found' is shown.",
    severity: "minor", tags: ["search"], frequency: "always",
    fix: "Search now matches partial email addresses, including the domain.", rootCause: "backend",
  },
  {
    id: "crm-contact-owner-filter",
    ...crm("Contacts"),
    title: "Owner filter on the contact list shows deactivated users only by email",
    description: "Deactivated owners appear as raw email addresses in the Owner filter.",
    steps: ["Open CRM › Contacts", "Open the Owner filter"],
    expected: "Every owner is listed by name, with '(inactive)' for people who left.",
    actual: "People who left are listed as their email address, for example farhan.kabir@hubone.example.com.",
    severity: "trivial", frequency: "always",
    fix: "The filter shows names for inactive users with an '(inactive)' label.", rootCause: "frontend",
  },
  {
    id: "crm-company-hierarchy",
    ...crm("Companies"),
    title: "Parent company shows the wrong number of subsidiaries",
    description: "A parent company with three subsidiaries shows '5 subsidiaries' on its page.",
    steps: ["Open CRM › Companies › Akij Group", "Look at the Subsidiaries count", "Open the Subsidiaries tab"],
    expected: "The count matches the three companies in the tab.",
    actual: "The count says 5; archived subsidiaries are counted too.",
    severity: "minor", frequency: "always",
    fix: "Archived subsidiaries are no longer counted.", rootCause: "backend",
  },
  {
    id: "crm-company-logo-upload",
    ...crm("Companies"),
    title: "Company logo upload fails for PNG files over 1 MB",
    description: "Uploading a company logo larger than 1 MB fails without an error message.",
    steps: ["Open a company in CRM", "Click the logo and choose a 1.4 MB PNG", "Click Save"],
    expected: "The logo is uploaded, or a message explains the size limit.",
    actual: "The spinner stops, the old logo stays and no message is shown.",
    severity: "minor", frequency: "always",
    fix: "Large logos are resized before upload, and failures show a message.", rootCause: "frontend",
  },
  {
    id: "crm-company-vat-validation",
    ...crm("Companies"),
    title: "Company form rejects valid Bangladeshi BIN numbers",
    description: "The Tax ID field only accepts the Norwegian organisation number format.",
    steps: ["Create a company with country Bangladesh", "Enter BIN 000123456-0101", "Click Save"],
    expected: "The company is saved with the BIN.",
    actual: "'Invalid organisation number' is shown.",
    severity: "major", tags: ["validation", "localization"], frequency: "always",
    fix: "Tax ID validation now follows the company's country.", rootCause: "frontend",
  },
  {
    id: "crm-lead-convert-owner",
    ...crm("Leads"),
    title: "Converting a lead assigns the new contact to the admin instead of the lead owner",
    description: "When a lead is converted, the resulting contact and deal are owned by the workspace admin.",
    steps: ["Open a lead owned by Sadia Rahman", "Click Convert and create a contact and a deal", "Open the new contact"],
    expected: "The contact and deal are owned by Sadia Rahman.",
    actual: "Both are owned by Mahmud Karim (the admin).",
    severity: "major", priority: "high", tags: ["ownership"], frequency: "always",
    fix: "Conversion keeps the lead owner for the contact and the deal.", rootCause: "backend",
  },
  {
    id: "crm-lead-score-negative",
    ...crm("Leads"),
    title: "Lead score can go below zero after unsubscribes",
    description: "Leads that unsubscribe from several emails show a negative score.",
    steps: ["Open CRM › Leads", "Sort by score, lowest first"],
    expected: "Scores are between 0 and 100.",
    actual: "Some leads show scores like -15.",
    severity: "minor", frequency: "always",
    fix: "Lead scores are clamped between 0 and 100.", rootCause: "backend",
    nab: { reason: "Negative scores are intentional: they mark leads sales should stop contacting. The help text now explains the range.", category: "works_as_designed" },
  },
  {
    id: "crm-lead-web-form-utm",
    ...crm("Leads"),
    title: "Leads from the website lose their campaign source",
    description: "UTM parameters from the landing page are not stored on web-to-lead submissions.",
    steps: ["Open hubone.example.com/contact?utm_source=facebook&utm_campaign=autumn", "Submit the form", "Open the new lead in CRM"],
    expected: "Source is 'facebook' and Campaign is 'autumn'.",
    actual: "Source and Campaign are empty.",
    severity: "major", tags: ["marketing"], frequency: "always",
    fix: "The form now passes UTM parameters through to the lead.", rootCause: "frontend",
  },
  {
    id: "crm-activity-timezone",
    ...crm("Activities"),
    title: "Logged calls show one hour off after daylight saving time changes",
    description: "Calls logged before the clock change are shown an hour later on the timeline.",
    steps: ["Open a contact with calls logged in March", "Look at the call times on the timeline"],
    expected: "Times are shown as they were logged.",
    actual: "Every call before 30 March is shown one hour later.",
    severity: "minor", tags: ["dates"], frequency: "always",
    fix: "Timeline times are converted with the offset at the time of the call.", rootCause: "frontend",
  },
  {
    id: "crm-activity-email-sync",
    ...crm("Activities"),
    title: "Emails sent from Outlook are not logged on the contact timeline",
    description: "With Outlook sync on, sent emails don't appear on the contact's timeline.",
    steps: ["Connect Outlook under Settings › Email sync", "Send an email to a contact from Outlook", "Open the contact in CRM after 10 minutes"],
    expected: "The email appears on the contact timeline.",
    actual: "Only received emails appear; sent emails are missing.",
    severity: "major", tags: ["integration"], frequency: "always",
    fix: "The sync now reads the Sent folder as well as the Inbox.", rootCause: "third_party",
  },
  {
    id: "crm-activity-task-reminder",
    ...crm("Activities"),
    title: "Follow-up task reminders are sent twice",
    description: "Reminders for follow-up tasks arrive twice, a minute apart.",
    steps: ["Create a follow-up task on a contact with a reminder in 5 minutes", "Wait for the reminder"],
    expected: "One reminder email and one notification.",
    actual: "Two identical emails and two notifications.",
    severity: "minor", frequency: "often",
    fix: "Reminder jobs are now locked so only one worker sends them.", rootCause: "infrastructure",
  },
  {
    id: "crm-import-duplicates",
    ...crm("Import & export"),
    title: "Contact import creates duplicates instead of updating existing contacts",
    description: "Importing a CSV with 'Update existing' chosen still creates new contacts for matching emails.",
    steps: ["Go to CRM › Import", "Upload contacts.csv with 200 existing emails", "Choose 'Update existing contacts (match on email)'", "Run the import"],
    expected: "The 200 contacts are updated; no new contacts are created.",
    actual: "200 new duplicate contacts are created.",
    severity: "critical", priority: "urgent", tags: ["import", "data-integrity"], frequency: "always",
    fix: "Email matching is now case-insensitive and ignores surrounding spaces.", rootCause: "backend",
  },
  {
    id: "crm-import-date-columns",
    ...crm("Import & export"),
    title: "Import reads birthdays in DD/MM format as MM/DD",
    description: "Dates in imported files are read in US format.",
    steps: ["Import a CSV with the Birthday column '03/09/1990'", "Open an imported contact"],
    expected: "Birthday is 3 September 1990.",
    actual: "Birthday is 9 March 1990.",
    severity: "minor", tags: ["dates", "import"], frequency: "always",
    fix: "The import asks for the date format and previews the first rows.", rootCause: "frontend",
  },
  {
    id: "crm-export-large",
    ...crm("Import & export"),
    title: "Exporting more than 10,000 contacts times out",
    description: "Large contact exports fail with a gateway timeout.",
    steps: ["Open CRM › Contacts with no filters (about 18,000 contacts)", "Click Export › Excel"],
    expected: "The export is prepared and emailed, or downloaded.",
    actual: "'504 Gateway Timeout' after one minute.",
    severity: "major", frequency: "always",
    fix: "Large exports now run in the background and are emailed when ready.", rootCause: "infrastructure",
  },
  {
    id: "crm-segment-count",
    ...crm("Segments"),
    title: "Segment member count differs from the list it shows",
    description: "A segment says 342 members but the list shows 318.",
    steps: ["Open CRM › Segments › 'Dhaka customers'", "Compare the count with the list length"],
    expected: "The count and the list match.",
    actual: "The count is 342; the list has 318 contacts.",
    severity: "minor", frequency: "always",
    fix: "The count now excludes unsubscribed and archived contacts, like the list.", rootCause: "backend",
  },
  {
    id: "crm-segment-and-or",
    ...crm("Segments"),
    title: "Segment rules combine 'OR' groups as 'AND'",
    description: "A segment with two OR conditions only returns contacts matching both.",
    steps: ["Create a segment: City is Dhaka OR City is Chattogram", "Save and open the segment"],
    expected: "Contacts from either city are in the segment.",
    actual: "The segment is empty.",
    severity: "major", frequency: "always",
    fix: "The rule builder now keeps the chosen operator when saving.", rootCause: "frontend",
  },
  {
    id: "crm-contact-merge-activities-again",
    ...crm("Contacts"),
    title: "Calls missing after merging duplicate contacts",
    description: "Merged contacts lose the call history of the duplicate.",
    steps: ["Merge two contacts for the same person", "Check the timeline"],
    expected: "All calls from both records are on the timeline.",
    actual: "Calls from the removed record are gone.",
    severity: "major", frequency: "always",
    fix: "Same fix as the merge activities bug.", rootCause: "backend",
    dupOf: "crm-contact-merge-activities",
  },

  // ------------------------------------------------------------------ HUB ONE · Sales
  {
    id: "sales-pipeline-drag",
    ...mod("sales", "Pipeline"),
    title: "Dragging a deal to 'Won' doesn't ask for the close date",
    description: "Deals moved to Won on the pipeline board skip the close date dialog.",
    steps: ["Open Sales › Pipeline", "Drag a deal from Negotiation to Won"],
    expected: "The close date and amount dialog opens.",
    actual: "The deal moves to Won with no close date, so it's missing from the forecast.",
    severity: "major", tags: ["pipeline"], frequency: "always",
    fix: "Moving to Won or Lost on the board opens the same dialog as the deal page.", rootCause: "frontend",
  },
  {
    id: "sales-deal-currency",
    ...mod("sales", "Deals"),
    title: "Deal amounts in BDT are converted to NOK twice in the pipeline total",
    description: "Pipeline totals are far too low when deals use a different currency.",
    steps: ["Create a deal of 1,000,000 BDT", "Open Sales › Pipeline with the currency set to NOK"],
    expected: "The deal counts as about 90,000 NOK.",
    actual: "The deal counts as about 8,100 NOK.",
    severity: "major", frequency: "always",
    fix: "Currency conversion now happens once, when totals are calculated.", rootCause: "backend",
  },
  {
    id: "sales-quote-pdf-vat",
    ...mod("sales", "Quotes"),
    title: "Quote PDF shows VAT as 0% for services",
    description: "Service lines on quotes show 0% VAT in the PDF although 15% is set.",
    steps: ["Create a quote with a service line (VAT 15%)", "Click Download PDF"],
    expected: "The PDF shows 15% VAT and the correct total.",
    actual: "VAT shows 0% and the total excludes VAT.",
    severity: "critical", priority: "high", tags: ["pdf", "tax"], frequency: "always",
    fix: "The PDF template reads the VAT rate per line.", rootCause: "backend",
  },
  {
    id: "sales-quote-expiry",
    ...mod("sales", "Quotes"),
    title: "Expired quotes can still be accepted by the customer",
    description: "Customers can accept quotes after the expiry date from the email link.",
    steps: ["Send a quote that expires tomorrow", "Open the customer link two days later", "Click Accept"],
    expected: "The page says the quote has expired.",
    actual: "The quote is accepted and a deal is marked Won.",
    severity: "major", frequency: "always",
    fix: "Acceptance checks the expiry date on the server.", rootCause: "backend",
  },
  {
    id: "sales-forecast-rounding",
    ...mod("sales", "Forecast"),
    title: "Forecast chart labels overlap on small screens",
    description: "Month labels on the forecast chart overlap below 1280 px width.",
    steps: ["Open Sales › Forecast on a 13-inch laptop"],
    expected: "Labels are readable.",
    actual: "Month labels overlap and can't be read.",
    severity: "trivial", frequency: "always",
    fix: "Labels are thinned out on narrow screens.", rootCause: "frontend",
  },

  // ------------------------------------------------------------------ HUB ONE · Support
  {
    id: "support-sla-weekend",
    ...mod("support", "SLA"),
    title: "SLA timer counts weekends for business-hours plans",
    description: "Tickets created on Thursday breach the 2-business-day SLA on Saturday.",
    steps: ["Create a ticket on Thursday at 15:00 for a customer on the Standard plan", "Check the SLA due time"],
    expected: "Due on Monday at 15:00.",
    actual: "Due on Saturday at 15:00, and the ticket is flagged as breached.",
    severity: "major", frequency: "always",
    fix: "The SLA calendar now skips weekends and holidays.", rootCause: "backend",
  },
  {
    id: "support-ticket-merge",
    ...mod("support", "Tickets"),
    title: "Merged tickets keep sending notifications from both threads",
    description: "After merging two tickets, the customer gets replies from both ticket numbers.",
    steps: ["Merge ticket #4410 into #4402", "Reply on #4402"],
    expected: "The customer gets one reply from #4402.",
    actual: "The customer gets two emails, one from each ticket.",
    severity: "minor", frequency: "always",
    fix: "Merged tickets unsubscribe the customer from the merged-away thread.", rootCause: "backend",
  },
  {
    id: "support-portal-attachment",
    ...mod("support", "Customer portal"),
    title: "Customers can't attach photos from a phone in the support portal",
    description: "The attachment button does nothing on iOS Safari.",
    steps: ["Open the customer portal on an iPhone", "Create a ticket and tap Attach"],
    expected: "The photo picker opens.",
    actual: "Nothing happens.",
    severity: "major", device: "iPhone 15", os: "iOS 17.5", browser: "Safari 17", frequency: "always",
    fix: "The file input is no longer hidden with display:none on iOS.", rootCause: "frontend",
  },
  {
    id: "support-ticket-crm-link",
    ...mod("support", "Tickets"),
    title: "Ticket sidebar shows the wrong CRM company for shared email domains",
    description: "Tickets from gmail.com addresses are linked to a random company.",
    steps: ["Receive a ticket from someone@gmail.com", "Look at the Company in the sidebar"],
    expected: "The contact's own company, or none.",
    actual: "The first company with a gmail.com contact is shown.",
    severity: "minor", frequency: "always",
    fix: "Public email domains are no longer used to match companies.", rootCause: "backend",
  },

  // ------------------------------------------------------------------ HUB ONE · Meetings
  {
    id: "meetings-google-sync",
    ...mod("meetings", "Calendar"),
    title: "Meetings moved in Google Calendar keep the old time in HUB ONE",
    description: "Rescheduling a synced meeting in Google Calendar doesn't update HUB ONE.",
    steps: ["Book a meeting in HUB ONE with Google sync on", "Move it by one hour in Google Calendar", "Open Meetings in HUB ONE"],
    expected: "The meeting shows the new time.",
    actual: "The old time is shown until the meeting is opened and saved again.",
    severity: "major", tags: ["integration"], frequency: "often",
    fix: "Google push notifications now update moved events.", rootCause: "third_party",
  },
  {
    id: "meetings-booking-link-tz",
    ...mod("meetings", "Scheduling"),
    title: "Booking page shows slots in the host's time zone instead of the visitor's",
    description: "Visitors abroad see and book the wrong times.",
    steps: ["Open a booking link from a computer set to Europe/Oslo", "Look at the available slots of a host in Asia/Dhaka"],
    expected: "Slots are shown in Oslo time.",
    actual: "Slots are shown in Dhaka time without saying so.",
    severity: "major", tags: ["dates"], frequency: "always",
    fix: "The booking page detects and shows the visitor's time zone.", rootCause: "frontend",
  },
  {
    id: "meetings-minutes-lost",
    ...mod("meetings", "Minutes"),
    title: "Meeting minutes are lost when two people edit at the same time",
    description: "When two attendees edit the minutes together, one person's notes are overwritten.",
    steps: ["Open the minutes of a meeting on two computers", "Type in both at the same time", "Reload"],
    expected: "Both people's notes are kept.",
    actual: "Only the last saved version is kept.",
    severity: "major", frequency: "sometimes",
    fix: "Minutes now use collaborative editing with merge.", rootCause: "frontend",
  },
  {
    id: "meetings-invite-language",
    ...mod("meetings", "Scheduling"),
    title: "Meeting invitations are always sent in English",
    description: "Invitations ignore the contact's preferred language.",
    steps: ["Set a contact's language to Bangla", "Invite them to a meeting"],
    expected: "The invitation is in Bangla.",
    actual: "The invitation is in English.",
    severity: "trivial", tags: ["localization"], frequency: "always",
    fix: "Invitations use the contact's language when a translation exists.", rootCause: "backend",
  },

  // ------------------------------------------------------------------ HUB ONE · Ledger
  {
    id: "ledger-invoice-number-gap",
    ...mod("ledger", "Invoices"),
    title: "Invoice numbers skip a number after a cancelled draft",
    description: "Cancelling a draft invoice leaves a gap in the invoice sequence.",
    steps: ["Create a draft invoice (INV-2026-0412)", "Cancel it", "Create and send a new invoice"],
    expected: "The new invoice is INV-2026-0412.",
    actual: "The new invoice is INV-2026-0413; 0412 is missing from the sequence.",
    severity: "major", tags: ["compliance"], frequency: "always",
    fix: "Invoice numbers are assigned when the invoice is sent, not when the draft is created.", rootCause: "backend",
  },
  {
    id: "ledger-payment-partial",
    ...mod("ledger", "Payments"),
    title: "Partial payments mark the invoice as paid",
    description: "Registering a partial payment sets the whole invoice to Paid.",
    steps: ["Open an invoice of 50,000 BDT", "Register a payment of 20,000 BDT"],
    expected: "Status is Partly paid with 30,000 BDT outstanding.",
    actual: "Status is Paid and the outstanding amount is 0.",
    severity: "critical", priority: "urgent", frequency: "always",
    fix: "Status is calculated from the sum of payments.", rootCause: "backend",
  },
  {
    id: "ledger-export-tripletex",
    ...mod("ledger", "Accounting export"),
    title: "Accounting export uses the wrong account for foreign-currency invoices",
    description: "Invoices in USD are exported to the NOK revenue account.",
    steps: ["Export September invoices to the accounting system", "Check the account for a USD invoice"],
    expected: "Account 3100 (foreign sales).",
    actual: "Account 3000 (domestic sales).",
    severity: "major", frequency: "always",
    fix: "The export maps accounts per currency.", rootCause: "configuration",
  },
  {
    id: "ledger-invoice-from-deal",
    ...mod("ledger", "Invoices"),
    title: "Invoice created from a won deal misses the deal's discount",
    description: "The 10% discount on a won deal is not copied to the invoice.",
    steps: ["Open a won deal with a 10% discount", "Click Create invoice"],
    expected: "The invoice shows the 10% discount.",
    actual: "The invoice has the full price.",
    severity: "major", frequency: "always",
    fix: "Discounts are copied from the deal lines.", rootCause: "backend",
  },

  // ------------------------------------------------------------------ HUB ONE · Stride
  {
    id: "stride-goal-progress",
    ...mod("stride", "Goals"),
    title: "Goal progress doesn't update when a key result is completed",
    description: "Completing a key result leaves the goal's progress bar unchanged.",
    steps: ["Open Stride › Goals › 'Grow CRM adoption'", "Mark one of the four key results as done"],
    expected: "Progress goes up to 25%.",
    actual: "Progress stays at 0% until the page is reloaded.",
    severity: "minor", frequency: "always",
    fix: "Goal progress is recalculated when a key result changes.", rootCause: "frontend",
  },
  {
    id: "stride-task-due-today",
    ...mod("stride", "Tasks"),
    title: "Tasks due today are listed under 'Overdue'",
    description: "Tasks due later today appear in the Overdue group.",
    steps: ["Create a task due today at 17:00", "Open Stride › My tasks at 10:00"],
    expected: "The task is in 'Due today'.",
    actual: "The task is in 'Overdue'.",
    severity: "minor", tags: ["dates"], frequency: "always",
    fix: "Due dates are compared in the user's time zone.", rootCause: "frontend",
  },
  {
    id: "stride-task-assign-guest",
    ...mod("stride", "Tasks"),
    title: "Tasks can be assigned to guests who can't open Stride",
    description: "Guest users appear in the assignee list but can't see their tasks.",
    steps: ["Open a task", "Assign it to a guest user", "Log in as the guest"],
    expected: "Guests are not offered as assignees, or can see the task.",
    actual: "The guest gets an email but 'No access' when opening the task.",
    severity: "minor", frequency: "always",
    fix: "Guests are removed from the assignee list.", rootCause: "backend",
  },

  // ------------------------------------------------------------------ HUB ONE · Quality
  {
    id: "quality-deviation-number",
    ...mod("quality", "Deviations"),
    title: "Two deviations get the same number when created at the same time",
    description: "Deviations created within a second of each other share a number.",
    steps: ["Two people create a deviation at the same moment", "Open Quality › Deviations"],
    expected: "Each deviation has its own number.",
    actual: "Both are DEV-0331.",
    severity: "major", frequency: "rarely",
    fix: "Deviation numbers come from a database sequence.", rootCause: "backend",
  },
  {
    id: "quality-capa-overdue-email",
    ...mod("quality", "Corrective actions"),
    title: "Overdue corrective actions don't notify the responsible person",
    description: "No reminder is sent when a corrective action passes its due date.",
    steps: ["Create a corrective action due yesterday", "Wait for the nightly reminder"],
    expected: "The responsible person gets a reminder.",
    actual: "No reminder is sent.",
    severity: "major", frequency: "always",
    fix: "The nightly job now includes corrective actions.", rootCause: "backend",
  },
  {
    id: "quality-document-version",
    ...mod("quality", "Documents"),
    title: "Approved document shows the draft version to readers",
    description: "After approving a new version, readers still open the previous draft.",
    steps: ["Approve version 3 of 'Complaint handling procedure'", "Open it as a reader"],
    expected: "Version 3 is shown.",
    actual: "The version 3 draft is shown with a 'Draft' watermark.",
    severity: "major", frequency: "always",
    fix: "Readers always get the latest approved version.", rootCause: "backend",
  },
  // ------------------------------------------------------------------ HUB ONE · CRM (more)
  {
    id: "crm-contact-archive-deals",
    ...crm("Contacts"),
    title: "Archiving a contact removes it from open deals",
    description: "Open deals lose their contact person when the contact is archived.",
    steps: ["Archive a contact who is the main contact on an open deal", "Open the deal in Sales"],
    expected: "The deal still shows the contact, marked as archived.",
    actual: "The deal's Contact field is empty.",
    severity: "major", frequency: "always",
    fix: "Archived contacts stay linked to deals and are labelled as archived.", rootCause: "backend",
  },
  {
    id: "crm-contact-bulk-owner",
    ...crm("Contacts"),
    title: "Bulk owner change only updates the first page of selected contacts",
    description: "Selecting all 180 contacts and changing the owner updates only 50.",
    steps: ["Open CRM › Contacts filtered by owner 'Farhan Kabir'", "Select all (180 contacts)", "Bulk actions › Change owner to Wahid Hasan"],
    expected: "All 180 contacts get the new owner.",
    actual: "Only the 50 contacts on the first page change; the rest keep Farhan Kabir.",
    severity: "major", priority: "high", tags: ["ownership", "bulk"], frequency: "always",
    fix: "Bulk actions apply to every selected contact, not just the visible page.", rootCause: "frontend",
  },
  {
    id: "crm-contact-birthday-reminder",
    ...crm("Contacts"),
    title: "Contact list 'Last activity' column sorts as text",
    description: "Sorting by Last activity puts 9 August after 10 September.",
    steps: ["Open CRM › Contacts", "Sort by Last activity"],
    expected: "Contacts are sorted by date.",
    actual: "Dates are sorted as text, so the order is wrong.",
    severity: "minor", frequency: "always",
    fix: "The column sorts on the stored date, not the formatted text.", rootCause: "frontend",
  },
  {
    id: "crm-company-duplicate-warning",
    ...crm("Companies"),
    title: "No duplicate warning when creating a company that already exists",
    description: "Creating 'Delta Traders Ltd' again gives no warning, and both records get contacts.",
    steps: ["Open CRM › Companies › New company", "Enter 'Delta Traders Ltd' (already exists)", "Click Save"],
    expected: "A warning suggests the existing company.",
    actual: "A second company is created without any warning.",
    severity: "minor", frequency: "always",
    fix: "The form suggests existing companies with a similar name or domain.", rootCause: "frontend",
  },
  {
    id: "crm-company-contacts-count",
    ...crm("Companies"),
    title: "Company Contacts tab shows 'No contacts' while loading",
    description: "The Contacts tab briefly says there are no contacts before the list appears.",
    steps: ["Open a company with 200 contacts", "Click the Contacts tab"],
    expected: "A loading state, then the contacts.",
    actual: "'No contacts' for about two seconds, then the list.",
    severity: "trivial", frequency: "always",
    fix: "The tab shows a loading state until the list arrives.", rootCause: "frontend",
  },
  {
    id: "crm-lead-assignment-rule",
    ...crm("Leads"),
    title: "Round-robin assignment skips reps who were on leave",
    description: "After returning from leave, a sales rep never gets new leads again.",
    steps: ["Mark Sadia Rahman as away for a week", "Mark her as available again", "Create five new leads"],
    expected: "Sadia gets her share of the new leads.",
    actual: "The leads go to the other reps only.",
    severity: "major", frequency: "always",
    fix: "Returning reps are put back into the rotation.", rootCause: "backend",
  },
  {
    id: "crm-lead-status-filter",
    ...crm("Leads"),
    title: "Lead status filter resets when opening a lead and going back",
    description: "The chosen status filter is lost after viewing a lead.",
    steps: ["Open CRM › Leads", "Filter by status 'Contacted'", "Open a lead and click Back"],
    expected: "The list is still filtered by 'Contacted'.",
    actual: "The filter is reset to 'All'.",
    severity: "minor", frequency: "always",
    fix: "Filters are kept in the address, so Back restores them.", rootCause: "frontend",
  },
  {
    id: "crm-activity-call-duration",
    ...crm("Activities"),
    title: "Call duration is saved in seconds but shown as minutes",
    description: "A 5-minute call is shown as '300 min' on the timeline.",
    steps: ["Log a call of 5 minutes on a contact", "Look at the call on the timeline"],
    expected: "The call shows 5 min.",
    actual: "The call shows 300 min.",
    severity: "minor", frequency: "always",
    fix: "The timeline converts seconds to minutes.", rootCause: "frontend",
  },
  {
    id: "crm-activity-edit-other",
    ...crm("Activities"),
    title: "Sales reps can edit calls logged by other people",
    description: "Anyone can change the notes of another person's call.",
    steps: ["Log in as a sales rep", "Open a contact and edit a call logged by someone else"],
    expected: "Only the author and admins can edit a call.",
    actual: "The call is changed and saved.",
    severity: "major", tags: ["permissions"], frequency: "always",
    fix: "Editing activities now checks the author or admin role.", rootCause: "backend",
  },
  {
    id: "crm-import-mapping-memory",
    ...crm("Import & export"),
    title: "Import forgets the column mapping on the second file",
    description: "Every import starts with an empty column mapping, even for the same template.",
    steps: ["Import contacts.csv and map the columns", "Import a second file with the same columns"],
    expected: "The previous mapping is suggested.",
    actual: "All columns must be mapped again.",
    severity: "trivial", frequency: "always",
    fix: "The last mapping is remembered per column set.", rootCause: "frontend",
  },
  {
    id: "crm-import-phone-leading-zero",
    ...crm("Import & export"),
    title: "Import drops the leading zero from local phone numbers",
    description: "Numbers like 01711 223344 are imported as 1711223344.",
    steps: ["Import a CSV with the phone number 01711 223344", "Open the imported contact"],
    expected: "The phone number is 01711 223344.",
    actual: "The phone number is 1711223344.",
    severity: "major", tags: ["import", "phone"], frequency: "always",
    fix: "Phone columns are read as text, never as numbers.", rootCause: "backend",
  },
  {
    id: "crm-segment-export",
    ...crm("Segments"),
    title: "Exporting a segment exports every contact instead",
    description: "The Export button on a segment downloads the whole contact list.",
    steps: ["Open CRM › Segments › 'Dhaka customers'", "Click Export › CSV"],
    expected: "The file has the 318 contacts in the segment.",
    actual: "The file has all 18,000 contacts.",
    severity: "major", frequency: "always",
    fix: "The export passes the segment's filter.", rootCause: "frontend",
  },
  {
    id: "sales-deal-stage-history",
    ...mod("sales", "Deals"),
    title: "Deal stage history misses changes made on the pipeline board",
    description: "Stage changes by drag and drop are not in the deal's history.",
    steps: ["Drag a deal from Qualified to Proposal", "Open the deal's history"],
    expected: "The history shows the move to Proposal.",
    actual: "Only changes made on the deal page are listed.",
    severity: "minor", frequency: "always",
    fix: "Board moves use the same update as the deal page.", rootCause: "backend",
  },
  {
    id: "support-ticket-crm-timeline",
    ...mod("support", "Tickets"),
    title: "Closed tickets don't appear on the contact's CRM timeline",
    description: "The contact timeline in CRM doesn't show support tickets.",
    steps: ["Close a ticket for Karim Ahmed", "Open Karim Ahmed in CRM"],
    expected: "The ticket is on the timeline.",
    actual: "No ticket is shown.",
    severity: "minor", frequency: "always",
    fix: "Ticket events are published to the CRM timeline.", rootCause: "backend",
  },
  {
    id: "meetings-crm-contact-link",
    ...mod("meetings", "Scheduling"),
    title: "Meetings booked from a contact aren't linked to the contact",
    description: "Booking a meeting from the contact page creates a meeting without the contact.",
    steps: ["Open a contact in CRM", "Click Book meeting and pick a time"],
    expected: "The meeting lists the contact as a guest and shows on their timeline.",
    actual: "The meeting has no guests.",
    severity: "major", frequency: "always",
    fix: "The contact is passed to the booking dialog.", rootCause: "frontend",
  },
  {
    id: "ledger-invoice-crm-company",
    ...mod("ledger", "Invoices"),
    title: "Invoice address isn't updated when the CRM company moves",
    description: "New invoices use the old address after a company's address is changed in CRM.",
    steps: ["Change the address of 'Delta Traders Ltd' in CRM", "Create a new invoice for Delta Traders Ltd"],
    expected: "The invoice uses the new address.",
    actual: "The invoice uses the old address.",
    severity: "major", frequency: "always",
    fix: "Invoices read the address from CRM when they are created.", rootCause: "backend",
  },
];
