// Background bug reports for the demo workspace. Each becomes one bug whose lifecycle is
// played out by the seeder (fixed, rejected, deferred, still open…).

import type { Frequency } from "../../core/types";

export interface BugTemplate {
  id: string;
  project: "sds" | "mob" | "sup";
  module: string;
  feature?: string;
  title: string;
  description: string;
  steps: string[];
  expected: string;
  actual: string;
  severity: "critical" | "major" | "minor" | "trivial";
  priority?: "urgent" | "high" | "medium" | "low";
  tags?: string[];
  frequency?: Frequency;
  browser?: string;
  device?: string;
  os?: string;
  version?: string;
  fix: string;
  rootCause?: "frontend" | "backend" | "data" | "configuration" | "third_party" | "infrastructure";
  /** Reason used if triage decides it is not a bug. */
  nab?: { reason: string; category: "works_as_designed" | "cannot_reproduce" | "configuration" | "test_data" | "third_party" };
  /** Reworded report of another template (becomes a duplicate when both exist). */
  dupOf?: string;
}

export const TEMPLATES: BugTemplate[] = [
  // ------------------------------------------------------------------ SDS Manager · EHS
  {
    id: "ehs-incident-date-utc",
    project: "sds", module: "ehs", feature: "Incident reports",
    title: "Incident date defaults to the next day after 22:00",
    description: "New incidents created late in the evening get tomorrow's date by default.",
    steps: ["Go to EHS › Incident reports", "Click New incident after 22:00 local time", "Leave the date field on its default"],
    expected: "The incident date defaults to today's local date.",
    actual: "The date field shows tomorrow's date.",
    severity: "minor", tags: ["dates"], frequency: "always", browser: "Chrome 128",
    fix: "Default the incident date from the user's time zone instead of UTC.", rootCause: "frontend",
  },
  {
    id: "ehs-risk-matrix-colours",
    project: "sds", module: "ehs", feature: "Risk assessments",
    title: "Risk matrix colours don't match the configured risk levels",
    description: "A likelihood 4 × consequence 3 cell is green although the company configured it as High.",
    steps: ["Go to Settings › Risk levels and set L4×C3 to High", "Open EHS › Risk assessments", "Open any assessment and look at the matrix"],
    expected: "The L4×C3 cell uses the High colour (orange).",
    actual: "The cell is green, the default Low colour.",
    severity: "major", tags: ["risk-matrix"], frequency: "always",
    fix: "Matrix now reads the company's configured levels instead of the built-in defaults.", rootCause: "frontend",
  },
  {
    id: "ehs-audit-percentage",
    project: "sds", module: "ehs", feature: "Audits",
    title: "Audit score goes above 100% when optional questions are answered",
    description: "Answering optional questions adds to the score but not to the maximum.",
    steps: ["Start the 'Warehouse storage' audit template", "Answer all required and optional questions with Yes", "Finish the audit"],
    expected: "The score is at most 100%.",
    actual: "The summary shows a score of 118%.",
    severity: "major", tags: ["audits", "calculation"], frequency: "always",
    fix: "Optional questions now count towards the maximum score only when answered.", rootCause: "backend",
  },
  {
    id: "ehs-incident-pdf-cutoff",
    project: "sds", module: "ehs", feature: "Incident reports",
    title: "Incident PDF cuts off witness statements after 1,000 characters",
    description: "Long witness statements are truncated in the exported PDF without any indication.",
    steps: ["Open an incident with a witness statement longer than 1,000 characters", "Click Export PDF", "Open the PDF"],
    expected: "The full witness statement is in the PDF.",
    actual: "The statement stops mid-sentence at about 1,000 characters.",
    severity: "major", tags: ["pdf"], frequency: "always",
    fix: "PDF template now wraps long text fields across pages.", rootCause: "backend",
  },
  {
    id: "ehs-remove-injured-person",
    project: "sds", module: "ehs", feature: "Incident reports",
    title: "Can't remove an injured person from an incident once added",
    description: "The remove icon next to an injured person does nothing.",
    steps: ["Open an incident in draft", "Add an injured person", "Click the remove icon next to the person"],
    expected: "The person is removed from the incident.",
    actual: "Nothing happens; the person stays on the list.",
    severity: "minor", frequency: "always", browser: "Firefox 130",
    fix: "Fixed the click handler on the remove button.", rootCause: "frontend",
  },
  {
    id: "ehs-copy-keeps-approval",
    project: "sds", module: "ehs", feature: "Risk assessments",
    title: "Copied risk assessment keeps the original's Approved status",
    description: "Copies should start as drafts but show Approved with the original approver's name.",
    steps: ["Open an approved risk assessment", "Click Copy", "Open the new copy"],
    expected: "The copy is a Draft without approval details.",
    actual: "The copy shows Approved by the original approver.",
    severity: "major", tags: ["approvals"], frequency: "always",
    fix: "Copy now resets status, approver and approval date.", rootCause: "backend",
  },
  {
    id: "ehs-audit-reminders-twice",
    project: "sds", module: "ehs", feature: "Audits",
    title: "Audit due-date reminder emails are sent twice",
    description: "Auditors receive two identical reminder emails a few seconds apart.",
    steps: ["Schedule an audit due tomorrow", "Wait for the 07:00 reminder run", "Check the auditor's inbox"],
    expected: "One reminder email.",
    actual: "Two identical reminder emails arrive within a minute.",
    severity: "minor", tags: ["email"], frequency: "often",
    fix: "Reminder job now takes a lock so only one worker sends reminders.", rootCause: "infrastructure",
  },
  {
    id: "ehs-my-site-filter",
    project: "sds", module: "ehs", feature: "Incident reports",
    title: "Incident list filter 'My site' shows incidents from all sites",
    description: "The My site filter is ignored for members placed at more than one site.",
    steps: ["Log in as a member placed at two sites", "Go to EHS › Incident reports", "Choose the My site filter"],
    expected: "Only incidents from the member's sites are listed.",
    actual: "Incidents from every site in the company are listed.",
    severity: "major", tags: ["filters"], frequency: "always",
    fix: "Filter now uses all of the member's placements.", rootCause: "backend",
  },
  {
    id: "ehs-heic-upload",
    project: "sds", module: "ehs", feature: "Audits",
    title: "Audit photo upload fails for HEIC images from iPhone",
    description: "Uploading photos taken on an iPhone shows a generic error.",
    steps: ["Open an audit question with photo evidence", "Upload a .heic photo from an iPhone", "Wait for the upload to finish"],
    expected: "The photo is uploaded and shown as a thumbnail.",
    actual: "'Upload failed' is shown and the photo is not attached.",
    severity: "major", tags: ["upload"], frequency: "always", browser: "Safari 17", device: "MacBook Air",
    fix: "HEIC photos are converted to JPEG on upload.", rootCause: "backend",
  },
  {
    id: "ehs-signature-date",
    project: "sds", module: "ehs", feature: "Risk assessments",
    title: "Risk assessment signature date uses US format",
    description: "Signature dates show as MM/DD/YYYY for Norwegian companies.",
    steps: ["Sign a risk assessment", "Look at the signature block"],
    expected: "The date uses the company's date format (DD.MM.YYYY).",
    actual: "The date is shown as 09/14/2026.",
    severity: "trivial", tags: ["dates", "localization"], frequency: "always",
    fix: "Signature block now formats dates with the company locale.", rootCause: "frontend",
  },

  // ------------------------------------------------------------------ SDS Manager · SDS Hub
  {
    id: "hub-cas-leading-zeros",
    project: "sds", module: "hub", feature: "SDS search",
    title: "SDS search doesn't find CAS numbers typed without leading zeros",
    description: "Searching 64-17-5 works but 0064-17-5 and the unformatted 64175 return nothing.",
    steps: ["Go to SDS Hub › Search", "Search for 64175", "Search for 0064-17-5"],
    expected: "Both searches find ethanol products.",
    actual: "No results for either search.",
    severity: "major", tags: ["search"], frequency: "always",
    fix: "CAS numbers are normalised before searching.", rootCause: "backend",
  },
  {
    id: "hub-upload-25mb",
    project: "sds", module: "hub", feature: "SDS upload",
    title: "Uploading an SDS larger than 25 MB fails silently",
    description: "Large scanned SDS files never finish uploading and no error is shown.",
    steps: ["Go to SDS Hub › Upload", "Select a 31 MB scanned PDF", "Click Upload"],
    expected: "Either the file uploads or a message explains the size limit.",
    actual: "The spinner runs for about a minute, then disappears. No file and no message.",
    severity: "major", tags: ["upload"], frequency: "always", browser: "Chrome 128",
    fix: "Show a clear error for files over the limit and raise the limit to 50 MB.", rootCause: "backend",
  },
  {
    id: "hub-revision-order",
    project: "sds", module: "hub", feature: "Revision tracking",
    title: "Revision history lists revisions in random order",
    description: "The revision history of an SDS is not sorted by revision date.",
    steps: ["Open an SDS with four or more revisions", "Open the Revision history tab"],
    expected: "Revisions are listed newest first.",
    actual: "Revisions appear in a different order on each reload.",
    severity: "minor", frequency: "often",
    fix: "Revisions are now sorted by revision date, newest first.", rootCause: "backend",
  },
  {
    id: "hub-request-status-pending",
    project: "sds", module: "hub", feature: "Supplier requests",
    title: "Supplier request stays Pending after the supplier uploads the SDS",
    description: "The request status is not updated when the supplier responds through the portal.",
    steps: ["Send a supplier request for a product", "As the supplier, upload the SDS in the Supplier Portal", "Open the request in SDS Hub"],
    expected: "The request shows Completed with the uploaded SDS linked.",
    actual: "The request still shows Pending; the SDS is in the Hub but not linked.",
    severity: "major", tags: ["supplier-requests"], frequency: "always",
    fix: "Portal uploads now publish an event that completes the matching request.", rootCause: "backend",
  },
  {
    id: "hub-filters-reset",
    project: "sds", module: "hub", feature: "SDS search",
    title: "Search filters reset when returning from an SDS detail page",
    description: "After opening a result and going back, all filters are cleared.",
    steps: ["Search SDS Hub with the filters Supplier = Henkel and Language = Norwegian", "Open a result", "Click Back"],
    expected: "The previous filters and results are kept.",
    actual: "Filters are cleared and all SDS are listed.",
    severity: "minor", tags: ["filters"], frequency: "always",
    fix: "Filters are stored in the URL so Back restores them.", rootCause: "frontend",
  },
  {
    id: "hub-swedish-h-phrases",
    project: "sds", module: "hub",
    title: "Hazard statements missing on the detail page for Swedish SDS",
    description: "H-phrases are extracted for Norwegian and English SDS but not Swedish ones.",
    steps: ["Open a Swedish-language SDS in SDS Hub", "Look at the Hazard statements section"],
    expected: "H-phrases from section 2 are listed.",
    actual: "The section says 'No hazard statements found'.",
    severity: "major", tags: ["extraction", "localization"], frequency: "always",
    fix: "Added Swedish section headings to the extraction rules.", rootCause: "data",
  },
  {
    id: "hub-download-previous-revision",
    project: "sds", module: "hub", feature: "Revision tracking",
    title: "Download SDS opens the previous revision",
    description: "The Download button on the SDS detail page serves the revision before the current one.",
    steps: ["Upload a new revision of an existing SDS", "Open the SDS detail page", "Click Download SDS"],
    expected: "The newest revision is downloaded.",
    actual: "The previous revision's PDF is downloaded.",
    severity: "critical", priority: "urgent", tags: ["revisions", "compliance"], frequency: "always",
    fix: "Download now resolves the current revision instead of a cached file id.", rootCause: "backend",
  },
  {
    id: "hub-duplicate-reupload",
    project: "sds", module: "hub", feature: "SDS upload",
    title: "Re-uploading the same file creates a duplicate SDS entry",
    description: "The Hub doesn't detect that an identical PDF was uploaded before.",
    steps: ["Upload an SDS PDF", "Upload the same PDF again"],
    expected: "A message says the SDS already exists.",
    actual: "A second, identical SDS entry is created.",
    severity: "minor", tags: ["duplicates"], frequency: "always",
    fix: "Uploads are checked against a content hash.", rootCause: "backend",
  },
  {
    id: "hub-autocomplete-deleted",
    project: "sds", module: "hub", feature: "SDS search",
    title: "Search suggestions include deleted products",
    description: "Autocomplete suggests products that were deleted weeks ago.",
    steps: ["Delete a product", "Type the product's name in the SDS Hub search box"],
    expected: "Deleted products are not suggested.",
    actual: "The deleted product is suggested and opens a 'not found' page.",
    severity: "minor", tags: ["search"], frequency: "always",
    fix: "Suggestion index is updated when products are deleted.", rootCause: "backend",
  },
  {
    id: "hub-reminder-wrong-contact",
    project: "sds", module: "hub", feature: "Supplier requests",
    title: "Supplier request reminders go to the old contact person",
    description: "After changing the supplier contact, reminders still go to the previous contact.",
    steps: ["Change the contact person on a supplier", "Wait for the weekly reminder of an open request"],
    expected: "The reminder goes to the new contact person.",
    actual: "The reminder goes to the previous contact.",
    severity: "major", tags: ["email", "supplier-requests"], frequency: "always",
    fix: "Reminders resolve the contact at send time.", rootCause: "backend",
  },
  {
    id: "hub-revision-compare-highlight",
    project: "sds", module: "hub", feature: "Revision tracking",
    title: "Revision comparison highlights sections that didn't change",
    description: "Sections with identical text are highlighted as changed because of whitespace differences.",
    steps: ["Open an SDS with two revisions", "Click Compare revisions"],
    expected: "Only changed sections are highlighted.",
    actual: "Sections 1, 4 and 9 are highlighted although the text is identical.",
    severity: "minor", frequency: "always",
    fix: "Comparison ignores whitespace-only differences.", rootCause: "backend",
  },

  // ------------------------------------------------------------------ SDS Manager · Members
  {
    id: "members-sort-last-login",
    project: "sds", module: "members",
    title: "Sorting members by last login puts never-logged-in members first",
    description: "Members who never logged in appear at the top when sorting by most recent login.",
    steps: ["Go to Members", "Sort by Last login, newest first"],
    expected: "Members who never logged in are listed last.",
    actual: "They are listed first.",
    severity: "trivial", frequency: "always",
    fix: "Empty values sort last.", rootCause: "frontend",
  },
  {
    id: "members-expired-invite",
    project: "sds", module: "members", feature: "Invite member",
    title: "Expired invitations can still be accepted",
    description: "An invitation older than 14 days can still be used to create an account.",
    steps: ["Invite a member", "Wait until the invitation has expired (or change its date on staging)", "Open the invitation link"],
    expected: "The link says the invitation expired and offers to request a new one.",
    actual: "The account is created and the person gets access.",
    severity: "major", priority: "high", tags: ["security"], frequency: "always",
    fix: "Invitation acceptance checks the expiry date on the server.", rootCause: "backend",
  },
  {
    id: "members-remove-placement",
    project: "sds", module: "members", feature: "Site placement",
    title: "Removing one site placement removes all of a member's placements",
    description: "Members placed at several sites lose every placement when one is removed.",
    steps: ["Open a member placed at Oslo and Bergen", "Remove the Bergen placement", "Save and reopen the member"],
    expected: "Only the Bergen placement is removed.",
    actual: "The member has no placements left.",
    severity: "critical", priority: "urgent", tags: ["data-loss"], frequency: "always",
    fix: "Removal now deletes the single placement instead of the member's placement set.", rootCause: "backend",
  },
  {
    id: "members-empty-role",
    project: "sds", module: "members", feature: "Roles & permissions",
    title: "A role can be saved without any permissions",
    description: "Custom roles can be saved with every permission switched off.",
    steps: ["Go to Members › Roles", "Create a role and switch off all permissions", "Click Save"],
    expected: "Validation asks for at least one permission.",
    actual: "The role is saved; members with it see an empty app.",
    severity: "minor", tags: ["validation"], frequency: "always",
    fix: "Added validation requiring at least one permission.", rootCause: "frontend",
    nab: { reason: "Empty roles are used deliberately to suspend access without deleting members.", category: "works_as_designed" },
  },
  {
    id: "members-email-case",
    project: "sds", module: "members",
    title: "Member search is case-sensitive for email addresses",
    description: "Searching Anna.Berg@ finds nothing although the member exists as anna.berg@.",
    steps: ["Go to Members", "Search for Anna.Berg@example.com"],
    expected: "The member anna.berg@example.com is found.",
    actual: "No members found.",
    severity: "minor", tags: ["search"], frequency: "always",
    fix: "Email search is case-insensitive.", rootCause: "backend",
  },
  {
    id: "members-bulk-role-50",
    project: "sds", module: "members", feature: "Roles & permissions",
    title: "Bulk role change only updates the first 50 selected members",
    description: "Selecting all 120 members and changing their role updates 50 of them.",
    steps: ["Go to Members and select all (120)", "Choose Change role › Viewer", "Confirm and check the list"],
    expected: "All 120 members get the Viewer role.",
    actual: "50 members are updated; the rest keep their old role. No error is shown.",
    severity: "major", tags: ["bulk"], frequency: "always",
    fix: "Bulk updates are paged through all selected members.", rootCause: "backend",
  },
  {
    id: "members-undefined-phone",
    project: "sds", module: "members", feature: "Edit member",
    title: "Member profile shows 'undefined' when the phone number is empty",
    description: "Profiles without a phone number show the word undefined.",
    steps: ["Open a member without a phone number"],
    expected: "The phone field is empty or shows a dash.",
    actual: "The phone field shows 'undefined'.",
    severity: "trivial", frequency: "always",
    fix: "Empty values are rendered as a dash.", rootCause: "frontend",
  },

  // ------------------------------------------------------------------ SDS Manager · Sites
  {
    id: "sites-move-building-address",
    project: "sds", module: "sites", feature: "Site hierarchy",
    title: "Moving a building to another site keeps the old site's address",
    description: "Buildings keep the previous parent's address after being moved.",
    steps: ["Go to Sites › Hierarchy", "Drag the building 'Lager B' from Oslo to Drammen", "Open the building"],
    expected: "The building shows the Drammen address.",
    actual: "The building still shows the Oslo address.",
    severity: "major", frequency: "always",
    fix: "Moving a node re-inherits the address unless it was set explicitly.", rootCause: "backend",
  },
  {
    id: "sites-export-column",
    project: "sds", module: "sites", feature: "Site list",
    title: "Site list export is missing the Storage locations column",
    description: "The Excel export leaves out a column that is visible on screen.",
    steps: ["Go to Sites", "Click Export to Excel", "Open the file"],
    expected: "The export has the same columns as the table, including Storage locations.",
    actual: "The Storage locations column is missing.",
    severity: "minor", tags: ["export"], frequency: "always",
    fix: "Export uses the visible column set.", rootCause: "backend",
  },
  {
    id: "sites-picker-freeze",
    project: "sds", module: "sites", feature: "Location picker",
    title: "Location picker freezes with more than 500 storage locations",
    description: "The browser tab stops responding for several seconds when opening the picker.",
    steps: ["Log in to a company with 600+ storage locations", "Open any product", "Click Change location"],
    expected: "The picker opens within a second.",
    actual: "The page freezes for 8–10 seconds before the picker appears.",
    severity: "major", tags: ["performance"], frequency: "always", browser: "Chrome 128",
    fix: "Picker loads the tree lazily and virtualises long lists.", rootCause: "frontend",
  },
  {
    id: "sites-delete-empty-location",
    project: "sds", module: "sites", feature: "Site hierarchy",
    title: "Deleting an empty storage location says it still has products",
    description: "Locations whose products were all moved can't be deleted.",
    steps: ["Move all products out of a storage location", "Try to delete the location"],
    expected: "The empty location is deleted.",
    actual: "'Location has products' is shown and nothing is deleted.",
    severity: "minor", frequency: "always",
    fix: "Deletion check ignores archived product links.", rootCause: "backend",
  },
  {
    id: "sites-tree-collapses",
    project: "sds", module: "sites", feature: "Site hierarchy",
    title: "Site tree collapses after renaming a node",
    description: "Renaming any node collapses the whole hierarchy.",
    steps: ["Expand three levels of the site tree", "Rename a building"],
    expected: "The tree stays expanded.",
    actual: "The tree collapses to the top level.",
    severity: "trivial", frequency: "always",
    fix: "Expanded state is kept across refreshes.", rootCause: "frontend",
  },
  {
    id: "sites-postcode-autocomplete",
    project: "sds", module: "sites", feature: "Site list",
    title: "Address autocomplete doesn't find Norwegian postcodes",
    description: "Typing a four-digit Norwegian postcode returns no suggestions.",
    steps: ["Create a site", "Type 0150 in the postcode field"],
    expected: "Oslo addresses are suggested.",
    actual: "No suggestions are shown.",
    severity: "minor", tags: ["localization"], frequency: "always",
    fix: "Country is passed to the address lookup.", rootCause: "third_party",
  },

  // ------------------------------------------------------------------ SDS Manager · Settings
  {
    id: "settings-transparent-logo",
    project: "sds", module: "settings", feature: "Company profile",
    title: "Company logo upload rejects transparent PNG files",
    description: "PNG logos with transparency fail validation.",
    steps: ["Go to Settings › Company profile", "Upload a transparent PNG logo"],
    expected: "The logo is accepted.",
    actual: "'Unsupported image' is shown.",
    severity: "minor", tags: ["upload"], frequency: "always",
    fix: "Image validation accepts RGBA PNGs.", rootCause: "backend",
  },
  {
    id: "settings-digest-off",
    project: "sds", module: "settings", feature: "Notifications",
    title: "Turning off the weekly digest email has no effect",
    description: "Members still receive the digest after switching it off.",
    steps: ["Go to Settings › Notifications", "Switch off Weekly digest and save", "Wait for Monday's digest"],
    expected: "No digest email is sent.",
    actual: "The digest email arrives as before.",
    severity: "major", tags: ["email"], frequency: "always",
    fix: "Digest job respects the per-member preference.", rootCause: "backend",
  },
  {
    id: "settings-api-key-visible",
    project: "sds", module: "settings", feature: "Integrations",
    title: "Integration API key is shown in full after saving",
    description: "The full API key is visible on the integrations page after saving.",
    steps: ["Go to Settings › Integrations", "Create an API key", "Save and reload the page"],
    expected: "Only the last four characters are shown.",
    actual: "The full key is displayed.",
    severity: "major", priority: "high", tags: ["security"], frequency: "always",
    fix: "Keys are masked after creation and only shown once.", rootCause: "frontend",
  },
  {
    id: "settings-language-menu",
    project: "sds", module: "settings", feature: "Language",
    title: "Switching language leaves the left menu in English",
    description: "After switching to Norwegian, the navigation menu stays in English until logout.",
    steps: ["Go to Settings › Language", "Choose Norsk", "Look at the left menu"],
    expected: "The menu is shown in Norwegian.",
    actual: "The menu stays in English until you log out and back in.",
    severity: "minor", tags: ["localization"], frequency: "always",
    fix: "Menu labels subscribe to language changes.", rootCause: "frontend",
  },
  {
    id: "settings-notifications-crash",
    project: "sds", module: "settings", feature: "Notifications",
    title: "Notification settings page shows an error when the member has no email",
    description: "Members created by import without an email can't open their notification settings.",
    steps: ["Log in as a member without an email address", "Go to Settings › Notifications"],
    expected: "The page opens and explains that email notifications need an address.",
    actual: "'Something went wrong' (500) is shown.",
    severity: "major", tags: ["error"], frequency: "always",
    fix: "Page handles members without email.", rootCause: "backend",
  },

  // ------------------------------------------------------------------ SDS Manager · Reports
  {
    id: "reports-empty-supplier",
    project: "sds", module: "reports", feature: "Chemical register export",
    title: "Chemical register Excel export has an empty Supplier column",
    description: "The Supplier column is blank for every row in the Excel export.",
    steps: ["Go to Reports › Chemical register", "Export to Excel", "Open the file"],
    expected: "The Supplier column shows each product's supplier.",
    actual: "The Supplier column is empty for all rows.",
    severity: "major", tags: ["export"], frequency: "always",
    fix: "Export joins the supplier table again after the schema change.", rootCause: "backend",
  },
  {
    id: "reports-exposure-double",
    project: "sds", module: "reports", feature: "Exposure report",
    title: "Exposure report counts products stored at two locations twice",
    description: "Totals are inflated for products stored in more than one location.",
    steps: ["Store a product at two locations", "Run the exposure report for the site"],
    expected: "The product is counted once per exposure group.",
    actual: "The product is counted twice and the total amount doubles.",
    severity: "major", tags: ["calculation"], frequency: "always",
    fix: "Exposure aggregation de-duplicates products per exposure group.", rootCause: "backend",
  },
  {
    id: "reports-dst",
    project: "sds", module: "reports", feature: "Scheduled reports",
    title: "Scheduled reports run an hour late after the daylight saving change",
    description: "Reports scheduled for 07:00 arrive at 08:00 since the clocks changed.",
    steps: ["Schedule a report for 07:00", "Wait for the first run after the DST change"],
    expected: "The report arrives at 07:00 local time.",
    actual: "The report arrives at 08:00.",
    severity: "minor", tags: ["dates"], frequency: "always",
    fix: "Schedules are stored in local time with the company time zone.", rootCause: "backend",
  },
  {
    id: "reports-filename-id",
    project: "sds", module: "reports", feature: "Chemical register export",
    title: "Register export file name uses the site ID instead of its name",
    description: "Exported files are named like register_4812.xlsx.",
    steps: ["Export the chemical register for a site"],
    expected: "The file is named after the site, for example register_Oslo_HQ.xlsx.",
    actual: "The file is named register_4812.xlsx.",
    severity: "trivial", tags: ["export"], frequency: "always",
    fix: "File name uses the sanitised site name.", rootCause: "backend",
  },
  {
    id: "reports-legend-overlap",
    project: "sds", module: "reports", feature: "Exposure report",
    title: "Exposure report chart legend overlaps the values in the A4 PDF",
    description: "In the PDF, the legend covers the right-hand bars.",
    steps: ["Run the exposure report", "Download as PDF (A4)"],
    expected: "Legend and values are readable.",
    actual: "The legend overlaps the last three bars.",
    severity: "minor", tags: ["pdf", "layout"], frequency: "always",
    fix: "Legend moved below the chart in print layouts.", rootCause: "frontend",
  },
  {
    id: "reports-slow-export",
    project: "sds", module: "reports", feature: "Chemical register export",
    title: "Register export takes over two minutes for 10,000 products",
    description: "Large companies wait minutes for the export and sometimes get a timeout.",
    steps: ["Log in to a company with 10,000+ products", "Export the chemical register"],
    expected: "The export finishes within 20 seconds or is emailed when ready.",
    actual: "It takes 2–3 minutes and times out about a third of the time.",
    severity: "major", tags: ["performance"], frequency: "often",
    fix: "Export runs as a background job and is streamed.", rootCause: "backend",
  },

  // ------------------------------------------------------------------ SDS Manager · Dashboard
  {
    id: "dash-expiring-archived",
    project: "sds", module: "dashboard", feature: "Widgets",
    title: "'Expiring SDS' widget counts archived documents",
    description: "The count includes SDS that were archived.",
    steps: ["Archive an SDS that expires next month", "Open the Dashboard"],
    expected: "Archived SDS are not counted.",
    actual: "The widget still counts it.",
    severity: "major", frequency: "always",
    fix: "Widget query excludes archived documents.", rootCause: "backend",
  },
  {
    id: "dash-overlap-1366",
    project: "sds", module: "dashboard", feature: "Widgets",
    title: "Dashboard widgets overlap on 1366×768 screens",
    description: "On laptop screens the inventory widget overlaps the risk widget.",
    steps: ["Open the Dashboard on a 1366×768 screen"],
    expected: "Widgets wrap to the next row.",
    actual: "The Chemical inventory widget covers half of the Risk widget.",
    severity: "minor", tags: ["layout"], frequency: "always", browser: "Edge 128",
    fix: "Grid switches to two columns below 1440px.", rootCause: "frontend",
  },
  {
    id: "dash-kpi-link",
    project: "sds", module: "dashboard", feature: "KPIs",
    title: "'Open incidents' KPI links to all incidents",
    description: "Clicking the tile opens the incident list without the Open filter.",
    steps: ["Click the Open incidents tile on the Dashboard"],
    expected: "The incident list opens filtered to open incidents.",
    actual: "All incidents are listed, including closed ones.",
    severity: "minor", frequency: "always",
    fix: "Tile link includes the status filter.", rootCause: "frontend",
  },
  {
    id: "dash-slow-40-sites",
    project: "sds", module: "dashboard",
    title: "Dashboard takes 12 seconds to load for companies with 40+ sites",
    description: "Large customers wait a long time for the Dashboard.",
    steps: ["Log in to a company with 40 or more sites", "Open the Dashboard"],
    expected: "The Dashboard loads within 3 seconds.",
    actual: "It takes about 12 seconds; widgets load one by one.",
    severity: "major", tags: ["performance"], frequency: "always",
    fix: "Widget queries are batched and cached for five minutes.", rootCause: "backend",
  },
  {
    id: "dash-stale-numbers",
    project: "sds", module: "dashboard", feature: "KPIs",
    title: "Dashboard shows yesterday's numbers until the page is refreshed",
    description: "KPIs don't update after midnight in an open tab.",
    steps: ["Leave the Dashboard open overnight", "Look at the KPIs in the morning"],
    expected: "KPIs refresh for the new day.",
    actual: "Yesterday's numbers are shown until reload.",
    severity: "minor", frequency: "always",
    fix: "KPIs refresh on focus and at midnight.", rootCause: "frontend",
  },
  {
    id: "dash-numbers-not-updating",
    project: "sds", module: "dashboard", feature: "KPIs",
    title: "KPI tiles don't update without reloading the page",
    description: "Numbers on the dashboard are out of date in a tab that has been open for a while.",
    steps: ["Keep the Dashboard open", "Register a new incident in another tab", "Return to the Dashboard"],
    expected: "The Open incidents KPI increases.",
    actual: "It stays the same until reload.",
    severity: "minor", frequency: "always",
    fix: "KPIs refresh on focus and at midnight.", rootCause: "frontend",
    dupOf: "dash-stale-numbers",
  },

  // ------------------------------------------------------------------ Mobile · Scanner
  {
    id: "mob-camera-denied-crash",
    project: "mob", module: "scanner", feature: "Barcode scan",
    title: "App crashes when camera permission is denied",
    description: "Denying camera access on first use closes the app.",
    steps: ["Install the app fresh", "Open Scan", "Tap Don't allow on the camera prompt"],
    expected: "The app explains why the camera is needed and offers to open settings.",
    actual: "The app closes immediately.",
    severity: "critical", priority: "urgent", tags: ["crash", "android"], frequency: "always", device: "Pixel 8", os: "Android 14", version: "3.7.2",
    fix: "Handle the denied permission state with an explanation screen.", rootCause: "frontend",
  },
  {
    id: "mob-ocr-o-slash",
    project: "mob", module: "scanner", feature: "Label OCR",
    title: "Label OCR reads 'ø' as 'o' in product names",
    description: "Norwegian product names are misread, so the product isn't matched.",
    steps: ["Scan the label of 'Rødsprit' with Label OCR"],
    expected: "The product 'Rødsprit' is found.",
    actual: "OCR reads 'Rodsprit' and finds nothing.",
    severity: "minor", tags: ["localization", "ocr"], frequency: "often", device: "iPhone 14", os: "iOS 17.5",
    fix: "OCR model configured with Norwegian language pack.", rootCause: "third_party",
  },
  {
    id: "mob-torch-stays-on",
    project: "mob", module: "scanner", feature: "Barcode scan",
    title: "Torch stays on after leaving the scanner",
    description: "The phone's torch keeps shining after closing the scanner.",
    steps: ["Open Scan", "Turn on the torch", "Go back to Home"],
    expected: "The torch turns off.",
    actual: "The torch stays on until the app is closed.",
    severity: "trivial", frequency: "always", device: "iPhone 13", os: "iOS 17.4",
    fix: "Torch is switched off when the camera session ends.", rootCause: "frontend",
  },
  {
    id: "mob-unknown-barcode-blank",
    project: "mob", module: "scanner", feature: "Barcode scan",
    title: "Scanning an unknown barcode shows a blank screen",
    description: "Barcodes that don't match a product lead to an empty white screen.",
    steps: ["Scan a barcode that isn't registered (e.g. a book)"],
    expected: "'No product found' with options to search or add the product.",
    actual: "A blank white screen; only the back button works.",
    severity: "major", frequency: "always", device: "Galaxy S23", os: "Android 14",
    fix: "Added the not-found state.", rootCause: "frontend",
  },
  {
    id: "mob-small-label-focus",
    project: "mob", module: "scanner", feature: "Barcode scan",
    title: "Scanner doesn't focus on small labels on iPhone 13 mini",
    description: "Small labels stay blurry and never scan on the mini model.",
    steps: ["Use an iPhone 13 mini", "Scan a 2 cm barcode label"],
    expected: "The camera focuses and scans.",
    actual: "The image stays blurry.",
    severity: "minor", frequency: "always", device: "iPhone 13 mini", os: "iOS 17.5",
    fix: "Enabled macro focus on supported devices.", rootCause: "frontend",
    nab: { reason: "The iPhone 13 mini can't focus closer than 12 cm; this is a hardware limit. Hold the phone further away and zoom.", category: "third_party" },
  },
  {
    id: "mob-double-scan",
    project: "mob", module: "scanner", feature: "Barcode scan",
    title: "Scanning quickly adds the same product twice",
    description: "When the barcode stays in view, the product is added to the stock count twice.",
    steps: ["Start a stock count", "Scan a barcode and keep it in view for a second"],
    expected: "The product is added once.",
    actual: "The product is added twice.",
    severity: "major", tags: ["duplicates"], frequency: "often", device: "Pixel 7", os: "Android 14",
    fix: "Debounce identical scans within two seconds.", rootCause: "frontend",
  },

  // ------------------------------------------------------------------ Mobile · Offline mode
  {
    id: "mob-cache-empty-after-update",
    project: "mob", module: "offline", feature: "Cached SDS",
    title: "Cached SDS list is empty after an app update",
    description: "After updating the app, offline SDS are gone until a manual sync.",
    steps: ["Cache SDS for offline use", "Update the app", "Open Offline documents without network"],
    expected: "Cached SDS are still available.",
    actual: "The list is empty until you go online and sync.",
    severity: "major", tags: ["offline"], frequency: "always", device: "iPhone 14", os: "iOS 17.5",
    fix: "Cache database is migrated instead of recreated on update.", rootCause: "data",
  },
  {
    id: "mob-sync-99",
    project: "mob", module: "offline", feature: "Sync",
    title: "Sync progress stops at 99% for accounts with 2,000+ products",
    description: "Large accounts never see sync complete.",
    steps: ["Log in to an account with more than 2,000 products", "Start a full sync"],
    expected: "Sync completes and shows the time of the last sync.",
    actual: "The progress bar stays at 99%.",
    severity: "minor", tags: ["offline", "performance"], frequency: "always", device: "Galaxy S23", os: "Android 14",
    fix: "Last page of the sync is acknowledged correctly.", rootCause: "backend",
  },
  {
    id: "mob-offline-edits-lost",
    project: "mob", module: "offline", feature: "Sync",
    title: "Offline stock edits are lost if the app is closed during sync",
    description: "Edits made offline disappear when the app is killed while syncing.",
    steps: ["Go offline and update stock for three products", "Go online and start sync", "Force-close the app during sync"],
    expected: "Unsynced edits are kept and sent on the next sync.",
    actual: "The edits are gone and never reach the server.",
    severity: "critical", priority: "high", tags: ["data-loss", "offline"], frequency: "often", device: "Pixel 8", os: "Android 14",
    fix: "Edits are removed from the outbox only after the server confirms them.", rootCause: "frontend",
  },
  {
    id: "mob-cache-after-logout",
    project: "mob", module: "offline", feature: "Cached SDS",
    title: "Cached SDS files aren't deleted after logout",
    description: "Documents from the previous user remain on the device after logging out.",
    steps: ["Cache SDS for offline use", "Log out", "Inspect the app's storage"],
    expected: "Cached documents are deleted on logout.",
    actual: "PDFs remain in the app's storage.",
    severity: "major", tags: ["security", "offline"], frequency: "always", device: "iPhone 14", os: "iOS 17.5",
    fix: "Logout clears the document cache.", rootCause: "frontend",
  },

  // ------------------------------------------------------------------ Mobile · Chemical inventory
  {
    id: "mob-negative-stock",
    project: "mob", module: "inventory", feature: "Stock updates",
    title: "Stock quantity accepts negative numbers",
    description: "Typing a minus sign lets you save a negative stock amount.",
    steps: ["Open a product in the inventory", "Tap Update stock", "Enter -5 and save"],
    expected: "Validation rejects negative amounts.",
    actual: "The stock is saved as -5 L.",
    severity: "minor", tags: ["validation"], frequency: "always", device: "Pixel 7", os: "Android 14",
    fix: "Added validation for non-negative amounts.", rootCause: "frontend",
  },
  {
    id: "mob-units-grams",
    project: "mob", module: "inventory", feature: "Inventory list",
    title: "Inventory shows grams for products registered in litres",
    description: "Liquid products are listed with the wrong unit.",
    steps: ["Register a product with the unit litres on the web", "Open the inventory list in the app"],
    expected: "The amount is shown in litres.",
    actual: "The amount is shown in grams (e.g. 5 g instead of 5 L).",
    severity: "major", frequency: "always", device: "iPhone 15", os: "iOS 17.5",
    fix: "App reads the product's unit instead of defaulting to grams.", rootCause: "frontend",
  },
  {
    id: "mob-refresh-filter",
    project: "mob", module: "inventory", feature: "Inventory list",
    title: "Pull-to-refresh resets the location filter",
    description: "Refreshing the list shows all locations again.",
    steps: ["Filter the inventory by a storage location", "Pull down to refresh"],
    expected: "The filter is kept.",
    actual: "All locations are shown again.",
    severity: "minor", tags: ["filters"], frequency: "always", device: "Galaxy S23", os: "Android 14",
    fix: "Filter state survives refresh.", rootCause: "frontend",
  },
  {
    id: "mob-saved-toast-offline",
    project: "mob", module: "inventory", feature: "Stock updates",
    title: "Stock update says 'Saved' when the request failed",
    description: "With a weak connection the app shows success although the update failed.",
    steps: ["Throttle the network", "Update a stock amount", "Check the web app"],
    expected: "The app shows that the update will be retried or failed.",
    actual: "'Saved' is shown but the web app still has the old amount.",
    severity: "major", frequency: "sometimes", device: "iPhone 14", os: "iOS 17.5",
    fix: "Toast waits for the server response; failures go to the outbox.", rootCause: "frontend",
  },
  {
    id: "mob-expiry-sort",
    project: "mob", module: "inventory", feature: "Inventory list",
    title: "Sorting by expiry date puts products without expiry at the top",
    description: "Products with no expiry date are listed first.",
    steps: ["Sort the inventory by Expiry date"],
    expected: "Products without expiry are listed last.",
    actual: "They are listed first.",
    severity: "trivial", frequency: "always", device: "Pixel 7", os: "Android 14",
    fix: "Empty expiry dates sort last.", rootCause: "frontend",
  },

  // ------------------------------------------------------------------ Mobile · Login
  {
    id: "mob-sso-loop",
    project: "mob", module: "login", feature: "SSO",
    title: "SSO login loops back to the login screen on Android 14",
    description: "Microsoft SSO completes but the app returns to the login screen.",
    steps: ["Open the app on Android 14", "Tap Sign in with Microsoft", "Complete the Microsoft login"],
    expected: "The user lands on Home.",
    actual: "The login screen is shown again; repeating gives the same result.",
    severity: "critical", priority: "urgent", tags: ["sso", "android"], frequency: "always", device: "Pixel 8", os: "Android 14", version: "3.7.1",
    fix: "Redirect URI registered for the Android 14 intent format.", rootCause: "configuration",
  },
  {
    id: "mob-reset-opens-web",
    project: "mob", module: "login", feature: "Password reset",
    title: "Password reset link opens the web app instead of the mobile app",
    description: "Links in the reset email open the browser on phones with the app installed.",
    steps: ["Request a password reset in the app", "Open the email on the same phone", "Tap the link"],
    expected: "The app opens on the reset screen.",
    actual: "The browser opens the web reset page.",
    severity: "minor", frequency: "always", device: "iPhone 15", os: "iOS 17.5",
    fix: "Universal links configured for the reset path.", rootCause: "configuration",
  },
  {
    id: "mob-onboarding-norwegian",
    project: "mob", module: "login",
    title: "Onboarding text is cut off in Norwegian",
    description: "Long Norwegian words overflow the onboarding cards.",
    steps: ["Set the phone language to Norwegian", "Install and open the app"],
    expected: "All onboarding text is visible.",
    actual: "The second card's text is cut off after 'Sikkerhetsdatabla…'.",
    severity: "trivial", tags: ["localization", "layout"], frequency: "always", device: "iPhone SE", os: "iOS 17.5",
    fix: "Onboarding text scales and wraps.", rootCause: "frontend",
  },
  {
    id: "mob-biometric-twice",
    project: "mob", module: "login",
    title: "Face ID prompt appears twice after unlocking the phone",
    description: "Returning to the app shows the biometric prompt twice in a row.",
    steps: ["Enable Face ID login", "Lock the phone with the app open", "Unlock and return to the app"],
    expected: "One Face ID prompt.",
    actual: "Two prompts in a row.",
    severity: "minor", frequency: "often", device: "iPhone 15", os: "iOS 17.5",
    fix: "Prompt is triggered only on the first foreground event.", rootCause: "frontend",
  },

  // ------------------------------------------------------------------ Supplier Portal · Document upload
  {
    id: "sup-bulk-stops",
    project: "sup", module: "upload", feature: "Bulk upload",
    title: "Bulk upload stops at the first file with an invalid name",
    description: "One bad file name aborts the rest of the batch.",
    steps: ["Select 20 SDS files where the third has a '#' in its name", "Start the bulk upload"],
    expected: "The invalid file is skipped and reported; the others upload.",
    actual: "Two files upload, then the batch stops with no message.",
    severity: "major", tags: ["bulk"], frequency: "always",
    fix: "Invalid files are reported and skipped.", rootCause: "frontend",
  },
  {
    id: "sup-future-revision",
    project: "sup", module: "upload", feature: "Validation",
    title: "Validation accepts SDS with a revision date in the future",
    description: "Files dated next year pass validation.",
    steps: ["Upload an SDS whose revision date is 2027-01-15"],
    expected: "A warning asks the supplier to confirm the date.",
    actual: "The file is accepted without a warning.",
    severity: "minor", tags: ["validation"], frequency: "always",
    fix: "Future revision dates show a warning.", rootCause: "backend",
    nab: { reason: "Suppliers may publish SDS ahead of a product launch. Future dates are allowed on purpose.", category: "works_as_designed" },
  },
  {
    id: "sup-progress-100",
    project: "sup", module: "upload", feature: "Bulk upload",
    title: "Upload progress shows 100% before processing is finished",
    description: "Suppliers leave the page thinking the upload is done while extraction is still running.",
    steps: ["Upload a large SDS", "Watch the progress bar"],
    expected: "Progress shows upload and processing separately.",
    actual: "100% is shown after transfer; processing continues for a minute without indication.",
    severity: "minor", frequency: "always",
    fix: "Progress shows a Processing step after upload.", rootCause: "frontend",
  },
  {
    id: "sup-zip-nested",
    project: "sup", module: "upload", feature: "Bulk upload",
    title: "ZIP files with nested folders import no documents",
    description: "Only files at the top level of the ZIP are imported.",
    steps: ["Upload a ZIP with SDS files inside sub-folders"],
    expected: "All PDFs in the ZIP are imported.",
    actual: "'0 documents imported'.",
    severity: "major", tags: ["bulk"], frequency: "always",
    fix: "ZIP import walks sub-folders.", rootCause: "backend",
  },
  {
    id: "sup-validation-english",
    project: "sup", module: "upload", feature: "Validation",
    title: "Validation messages are only in English",
    description: "Suppliers using the portal in German see English validation messages.",
    steps: ["Switch the portal language to Deutsch", "Upload a file with a missing product name"],
    expected: "The validation message is in German.",
    actual: "The message is in English.",
    severity: "minor", tags: ["localization"], frequency: "always",
    fix: "Validation messages are translated.", rootCause: "frontend",
  },


  // ------------------------------------------------------------------ Supplier Portal · Product catalogue
  {
    id: "sup-variants-separate",
    project: "sup", module: "catalogue", feature: "Product search",
    title: "Product search lists variants as separate products",
    description: "Each packaging variant shows up as its own product in search.",
    steps: ["Search for a product with three packaging variants"],
    expected: "One product with three variants.",
    actual: "Three separate products with the same name.",
    severity: "minor", frequency: "always",
    fix: "Search groups variants under their product.", rootCause: "backend",
  },
  {
    id: "sup-ufi-variant",
    project: "sup", module: "catalogue", feature: "Product details",
    title: "Product details show the wrong UFI code for variants",
    description: "All variants show the UFI of the first variant.",
    steps: ["Open a product with variants that have different UFI codes", "Switch between variants"],
    expected: "Each variant shows its own UFI code.",
    actual: "All variants show the first variant's UFI.",
    severity: "major", tags: ["compliance"], frequency: "always",
    fix: "UFI is read from the selected variant.", rootCause: "frontend",
  },
  {
    id: "sup-csv-commas",
    project: "sup", module: "catalogue",
    title: "Catalogue CSV export breaks on product names with commas",
    description: "Names like 'Cleaner, 5 L' shift the remaining columns.",
    steps: ["Export the catalogue to CSV", "Open it in Excel"],
    expected: "Each product is on one row with correct columns.",
    actual: "Columns shift for products with commas in the name.",
    severity: "major", tags: ["export"], frequency: "always",
    fix: "CSV values are quoted.", rootCause: "backend",
  },
  {
    id: "sup-stretched-images",
    project: "sup", module: "catalogue", feature: "Product details",
    title: "Product images are stretched on the details page",
    description: "Portrait images are distorted to fit a square box.",
    steps: ["Open a product with a portrait-oriented image"],
    expected: "The image keeps its proportions.",
    actual: "The image is stretched horizontally.",
    severity: "trivial", tags: ["layout"], frequency: "always",
    fix: "Images use object-fit: contain.", rootCause: "frontend",
  },
  {
    id: "sup-download-hidden-mobile",
    project: "sup", module: "catalogue", feature: "Product details",
    title: "'Download SDS' button is hidden on small screens",
    description: "On phones the button is pushed off-screen.",
    steps: ["Open a product on a 375px-wide screen"],
    expected: "The Download SDS button is visible.",
    actual: "The button is off-screen and can't be reached.",
    severity: "minor", tags: ["layout", "mobile"], frequency: "always", browser: "Safari (iOS 17)",
    fix: "Action bar wraps on small screens.", rootCause: "frontend",
  },

  // ------------------------------------------------------------------ Supplier Portal · Account
  {
    id: "sup-vat-format",
    project: "sup", module: "account", feature: "Registration",
    title: "Registration accepts invalid VAT numbers",
    description: "Any text is accepted in the VAT number field.",
    steps: ["Open supplier registration", "Enter 'ABC' as VAT number and submit"],
    expected: "Validation asks for a valid VAT number.",
    actual: "Registration succeeds with VAT number 'ABC'.",
    severity: "minor", tags: ["validation"], frequency: "always",
    fix: "VAT numbers are validated per country.", rootCause: "backend",
  },
  {
    id: "sup-admin-remove-self",
    project: "sup", module: "account", feature: "Company users",
    title: "The only company admin can remove themselves",
    description: "Removing the last admin locks the supplier out of user management.",
    steps: ["Log in as the only admin of a supplier company", "Go to Company users", "Remove yourself"],
    expected: "Blocked: a company needs at least one admin.",
    actual: "The admin is removed and nobody can manage users any more.",
    severity: "major", frequency: "always",
    fix: "At least one admin is enforced.", rootCause: "backend",
  },
  {
    id: "sup-pending-invites",
    project: "sup", module: "account", feature: "Company users",
    title: "Company users list doesn't show pending invitations",
    description: "Invited users don't appear until they accept.",
    steps: ["Invite a colleague", "Open Company users"],
    expected: "The invitation is listed as pending.",
    actual: "The invited person is not listed.",
    severity: "minor", frequency: "always",
    fix: "Pending invitations are listed with a resend option.", rootCause: "frontend",
  },
  {
    id: "sup-confirmation-spam",
    project: "sup", module: "account", feature: "Registration",
    title: "Registration confirmation email lands in spam",
    description: "Confirmation emails from the staging portal go to spam in Gmail.",
    steps: ["Register a new supplier on staging with a Gmail address", "Check the inbox"],
    expected: "The confirmation email arrives in the inbox.",
    actual: "It arrives in Spam.",
    severity: "major", tags: ["email"], frequency: "always",
    fix: "Configured DKIM for the staging mail domain.", rootCause: "configuration",
    nab: { reason: "Staging uses an unverified mail domain; production has DKIM and SPF configured. Not reproducible in production.", category: "configuration" },
  },
  {
    id: "sup-session-5min",
    project: "sup", module: "account",
    title: "Supplier Portal logs users out after 5 minutes",
    description: "Suppliers filling in product data are logged out quickly.",
    steps: ["Log in to the Supplier Portal", "Leave the product form open for 6 minutes", "Click Save"],
    expected: "The session lasts at least 30 minutes of inactivity.",
    actual: "The user is logged out and the form data is lost.",
    severity: "major", tags: ["session"], frequency: "always",
    fix: "Session timeout set to 30 minutes with a warning before logout.", rootCause: "configuration",
  },
  {
    id: "sup-session-short",
    project: "sup", module: "account",
    title: "Logged out of the Supplier Portal while editing a product",
    description: "Work is lost because the session ends while editing.",
    steps: ["Edit a product for a few minutes", "Save"],
    expected: "The product is saved.",
    actual: "The login page is shown and the changes are lost.",
    severity: "major", tags: ["session"], frequency: "often",
    fix: "Session timeout set to 30 minutes with a warning before logout.", rootCause: "configuration",
    dupOf: "sup-session-5min",
  },
  {
    id: "hub-cas-search-zero",
    project: "sds", module: "hub", feature: "SDS search",
    title: "CAS number search finds nothing without hyphens",
    description: "Typing a CAS number without hyphens returns no results.",
    steps: ["Search SDS Hub for 7732185"],
    expected: "Water products (CAS 7732-18-5) are found.",
    actual: "No results.",
    severity: "major", tags: ["search"], frequency: "always",
    fix: "CAS numbers are normalised before searching.", rootCause: "backend",
    dupOf: "hub-cas-leading-zeros",
  },
  {
    id: "mob-sync-lost-edits",
    project: "mob", module: "offline", feature: "Sync",
    title: "Stock changes made offline disappear after going online",
    description: "Some offline stock updates never show up on the web.",
    steps: ["Update stock offline", "Go online and open the app briefly", "Check the web app"],
    expected: "All offline changes appear on the web.",
    actual: "Some changes are missing.",
    severity: "critical", tags: ["data-loss", "offline"], frequency: "sometimes", device: "Galaxy S23", os: "Android 14",
    fix: "Edits are removed from the outbox only after the server confirms them.", rootCause: "frontend",
    dupOf: "mob-offline-edits-lost",
  },
];

export const NAB_FALLBACKS: { reason: string; category: "cannot_reproduce" | "test_data" | "configuration" }[] = [
  { reason: "Can't reproduce on the current build with the steps given. Please reopen with a screen recording if it happens again.", category: "cannot_reproduce" },
  { reason: "The test company had an expired licence, which hides this feature. Works with a valid licence.", category: "test_data" },
  { reason: "Caused by a browser extension blocking scripts. Works in a clean profile.", category: "configuration" },
];

export const DEFER_REASONS = [
  { reason: "Low impact and a workaround exists. Scheduled with the reporting redesign.", target: "Reporting redesign (Q1)" },
  { reason: "Depends on the new permissions model; revisit after it ships.", target: "Permissions v2" },
  { reason: "Affects only a handful of legacy accounts; will be handled in the migration project.", target: "Legacy migration" },
];

export const ENGINEER_NOTES = [
  "Reproduced on staging. Looking into it.",
  "Found the cause; a fix is in review.",
  "This touches shared code, so I'm adding a test before changing it.",
  "Pairing with {other} on this one.",
];

export const QA_NOTES = [
  "Also happens in Firefox.",
  "Still reproducible on today's staging build.",
  "Customer support has had two tickets about this.",
  "Retested after the last deploy; no change.",
];
