import { useNavigate } from 'react-router-dom'
import { Bell, CheckCheck, Gift, Megaphone, Package, Settings2, Headphones, Trash2 } from 'lucide-react'
import type { AppNotification } from '../data/types'
import { useStore } from '../store/store'
import { confirmDialog } from '../store/toast'
import { cx, timeAgo } from '../lib/format'
import { useTitle } from '../lib/hooks'
import { EmptyState } from '../components/ui'

const ICON = { order: Package, voucher: Gift, promo: Megaphone, system: Settings2, support: Headphones }
const COLOR = { order: 'bg-brand-100 text-brand-700', voucher: 'bg-coral-100 text-coral-700', promo: 'bg-amber-100 text-amber-800', system: 'bg-ink-100 text-ink-700', support: 'bg-sky-100 text-sky-700' }

export default function Notifications() {
  useTitle('Notifications')
  const nav = useNavigate()
  const uid = useStore((s) => s.currentUserId)
  const all = useStore((s) => s.db.notifications)
  const promos = useStore((s) => s.settings.notifyPromos)
  const markRead = useStore((s) => s.markRead)
  const markAll = useStore((s) => s.markAllRead)
  const clear = useStore((s) => s.clearNotifications)
  const mine = all.filter((n) => n.userId === uid && (promos || n.type !== 'promo')).sort((a, b) => b.createdAt - a.createdAt)
  const today = mine.filter((n) => Date.now() - n.createdAt < 864e5)
  const earlier = mine.filter((n) => Date.now() - n.createdAt >= 864e5)
  const open = (n: AppNotification) => {
    markRead(n.id)
    if (n.link) nav(n.link)
  }
  const Group = ({ title, items }: { title: string; items: AppNotification[] }) =>
    items.length ? (
      <section className="mt-5">
        <p className="mb-2 text-xs font-bold uppercase tracking-wide text-ink-400">{title}</p>
        <div className="card divide-y divide-ink-100 overflow-hidden">
          {items.map((n) => {
            const Icon = ICON[n.type]
            return (
              <button key={n.id} onClick={() => open(n)} className={cx('flex w-full items-start gap-3 p-4 text-left transition hover:bg-ink-50', !n.read && 'bg-brand-50/50')}>
                <span className={cx('grid size-10 shrink-0 place-items-center rounded-full', COLOR[n.type])}><Icon className="size-[18px]" /></span>
                <span className="min-w-0 flex-1">
                  <span className="flex items-start justify-between gap-2">
                    <span className={cx('text-sm', n.read ? 'font-semibold' : 'font-bold')}>{n.title}</span>
                    <span className="shrink-0 text-xs text-ink-400">{timeAgo(n.createdAt)}</span>
                  </span>
                  <span className="block text-[13px] text-ink-500">{n.body}</span>
                </span>
                {!n.read && <span className="mt-1.5 size-2 shrink-0 rounded-full bg-coral-500" />}
              </button>
            )
          })}
        </div>
      </section>
    ) : null
  return (
    <div className="mx-auto max-w-3xl px-4 py-6 animate-fade-in">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h1 className="font-display text-3xl font-extrabold">Notifications</h1>
        {mine.length > 0 && (
          <div className="flex gap-1">
            <button className="btn btn-ghost btn-sm" onClick={markAll}><CheckCheck className="size-4" /> Mark all read</button>
            <button className="btn btn-ghost btn-sm text-red-600" onClick={async () => { if (await confirmDialog({ title: 'Clear all notifications?', confirmLabel: 'Clear', tone: 'danger' })) clear() }}><Trash2 className="size-4" /> Clear</button>
          </div>
        )}
      </div>
      {mine.length === 0 ? <EmptyState emoji="🔔" title="You're all caught up" body="Order updates, voucher drops and promos will appear here." /> : (
        <>
          <Group title="Today" items={today} />
          <Group title="Earlier" items={earlier} />
        </>
      )}
      <p className="mt-6 flex items-center gap-2 text-xs text-ink-500"><Bell className="size-4" /> All notifications are generated by the simulation.</p>
    </div>
  )
}
