// AUTO-GENERATED by the photo build script. Bundled, compressed photos (WebP) served from public/img.
// Sources and licences: public/img/CREDITS.md

export const FOOD_PHOTOS = {
  "biriyani": [
    "img/f/biryani-biryani1.webp",
    "img/f/biryani-biryani4.webp",
    "img/f/biryani-biryani7.webp",
    "img/f/biryani-biryani8.webp",
    "img/f/biryani-biryani11.webp",
    "img/f/biryani-biryani14.webp",
    "img/f/biryani-biryani15.webp",
    "img/f/biryani-biryani16.webp",
    "img/f/biryani-biryani17.webp",
    "img/f/biryani-biryani26.webp",
    "img/f/biryani-biryani27.webp",
    "img/f/biryani-biryani28.webp",
    "img/f/biryani-biryani31.webp",
    "img/f/biryani-biryani32.webp"
  ],
  "polao": [
    "img/f/biryani-biryani3.webp",
    "img/f/biryani-biryani2.webp",
    "img/f/biryani-biryani40.webp",
    "img/f/biryani-biryani25.webp",
    "img/f/biryani-biryani50.webp",
    "img/f/biryani-biryani81.webp"
  ],
  "grill": [
    "img/f/biryani-biryani66.webp",
    "img/f/biryani-biryani21.webp",
    "img/f/butter-chicken-butter-chicken12.webp",
    "img/f/biryani-biryani5.webp",
    "img/f/biryani-biryani34.webp",
    "img/f/biryani-biryani81.webp"
  ],
  "burger": [
    "img/f/burger-burger1.webp",
    "img/f/burger-burger3.webp",
    "img/f/burger-burger4.webp",
    "img/f/burger-burger5.webp",
    "img/f/burger-burger8.webp",
    "img/f/burger-burger9.webp",
    "img/f/burger-burger12.webp",
    "img/f/burger-burger14.webp",
    "img/f/burger-burger17.webp",
    "img/f/burger-burger18.webp",
    "img/f/burger-burger21.webp",
    "img/f/burger-burger22.webp",
    "img/f/burger-burger24.webp",
    "img/f/burger-burger25.webp"
  ],
  "chicken": [
    "img/f/burger-burger31.webp",
    "img/f/burger-burger69.webp",
    "img/f/biryani-biryani66.webp",
    "img/f/biryani-biryani21.webp",
    "img/f/burger-burger82.webp",
    "img/f/biryani-biryani5.webp"
  ],
  "fries": [
    "img/f/burger-burger6.webp",
    "img/f/burger-burger10.webp",
    "img/f/burger-burger52.webp",
    "img/f/burger-burger60.webp",
    "img/f/burger-burger61.webp",
    "img/f/burger-burger49.webp"
  ],
  "curry": [
    "img/f/butter-chicken-butter-chicken1.webp",
    "img/f/butter-chicken-butter-chicken3.webp",
    "img/f/butter-chicken-butter-chicken4.webp",
    "img/f/butter-chicken-butter-chicken6.webp",
    "img/f/butter-chicken-butter-chicken7.webp",
    "img/f/butter-chicken-butter-chicken8.webp",
    "img/f/butter-chicken-butter-chicken10.webp",
    "img/f/butter-chicken-butter-chicken11.webp",
    "img/f/butter-chicken-butter-chicken13.webp",
    "img/f/butter-chicken-butter-chicken14.webp"
  ],
  "desserts": [
    "img/f/dessert-dessert5.webp",
    "img/f/dessert-dessert6.webp",
    "img/f/dessert-dessert7.webp",
    "img/f/dessert-dessert36.webp",
    "img/f/dessert-dessert34.webp",
    "img/f/dessert-dessert14.webp",
    "img/f/dessert-dessert9.webp",
    "img/f/dessert-dessert30.webp",
    "img/f/dessert-dessert8.webp",
    "img/f/dessert-dessert24.webp",
    "img/f/dessert-dessert26.webp",
    "img/f/dessert-dessert27.webp",
    "img/f/dessert-dessert11.webp",
    "img/f/dessert-dessert13.webp"
  ],
  "sweets": [
    "img/f/dessert-dessert21.webp",
    "img/f/dessert-dessert19.webp",
    "img/f/dessert-dessert10.webp",
    "img/f/dessert-dessert13.webp",
    "img/f/dessert-dessert27.webp",
    "img/f/dessert-dessert12.webp"
  ],
  "yogurt": [
    "img/f/dessert-dessert3.webp",
    "img/f/dessert-dessert18.webp",
    "img/f/dessert-dessert31.webp",
    "img/f/dessert-dessert34.webp"
  ],
  "drinks": [
    "img/f/dessert-dessert35.webp",
    "img/f/dessert-dessert29.webp",
    "img/f/dessert-dessert25.webp",
    "img/f/dessert-dessert18.webp",
    "img/f/dessert-dessert31.webp",
    "img/f/dessert-dessert3.webp"
  ],
  "coffee": [
    "img/f/dessert-dessert29.webp",
    "img/f/dessert-dessert4.webp",
    "img/f/dessert-dessert16.webp",
    "img/f/dessert-dessert32.webp",
    "img/f/dessert-dessert33.webp",
    "img/f/dessert-dessert11.webp"
  ],
  "chinese": [
    "img/f/rice-rice1.webp",
    "img/f/rice-rice2.webp",
    "img/f/rice-rice3.webp",
    "img/f/rice-rice4.webp",
    "img/f/rice-rice5.webp",
    "img/f/rice-rice6.webp",
    "img/f/rice-rice7.webp",
    "img/f/rice-rice8.webp",
    "img/f/rice-rice9.webp",
    "img/f/rice-rice10.webp"
  ],
  "noodles": [
    "img/f/rice-rice16.webp",
    "img/f/pasta-pasta2.webp",
    "img/f/pasta-pasta8.webp",
    "img/f/pasta-pasta15.webp",
    "img/f/pasta-pasta17.webp",
    "img/f/pasta-pasta13.webp"
  ],
  "japanese": [
    "img/f/rice-rice30.webp",
    "img/f/rice-rice16.webp",
    "img/f/rice-rice29.webp",
    "img/f/rice-rice34.webp",
    "img/f/rice-rice22.webp"
  ],
  "snacks": [
    "img/f/samosa-samosa1.webp",
    "img/f/samosa-samosa2.webp",
    "img/f/samosa-samosa3.webp",
    "img/f/samosa-samosa4.webp",
    "img/f/samosa-samosa5.webp",
    "img/f/samosa-samosa6.webp",
    "img/f/samosa-samosa7.webp",
    "img/f/samosa-samosa8.webp",
    "img/f/samosa-samosa9.webp",
    "img/f/samosa-samosa10.webp"
  ],
  "pizza": [
    "img/f/pizza-pizza1.webp",
    "img/f/pizza-pizza2.webp",
    "img/f/pizza-pizza3.webp",
    "img/f/pizza-pizza4.webp",
    "img/f/pizza-pizza6.webp",
    "img/f/pizza-pizza7.webp",
    "img/f/pizza-pizza8.webp",
    "img/f/pizza-pizza9.webp",
    "img/f/pizza-pizza11.webp",
    "img/f/pizza-pizza12.webp",
    "img/f/pizza-pizza14.webp",
    "img/f/pizza-pizza16.webp"
  ],
  "pasta": [
    "img/f/pasta-pasta3.webp",
    "img/f/pasta-pasta4.webp",
    "img/f/pasta-pasta6.webp",
    "img/f/pasta-pasta7.webp",
    "img/f/pasta-pasta9.webp",
    "img/f/pasta-pasta10.webp",
    "img/f/pasta-pasta11.webp",
    "img/f/pasta-pasta13.webp"
  ],
  "healthy": [
    "img/f/pasta-pasta14.webp",
    "img/f/rice-rice34.webp",
    "img/f/rice-rice35.webp",
    "img/f/rice-rice22.webp",
    "img/f/pasta-pasta6.webp",
    "img/f/pasta-pasta7.webp"
  ]
} as const

export type FoodPool = keyof typeof FOOD_PHOTOS

/** Product photos keyed by catalog photo code: one image per available colour, plus an optional back view. */
export const PRODUCT_PHOTOS: Record<string, { colors: Record<string, string>; back: string | null; extra: string[] }> = {
  "ms04": {
    "colors": {
      "black": "img/p/ms04-black.webp",
      "orange": "img/p/ms04-orange.webp",
      "red": "img/p/ms04-red.webp"
    },
    "back": null,
    "extra": []
  },
  "ms11": {
    "colors": {
      "blue": "img/p/ms11-blue.webp",
      "green": "img/p/ms11-green.webp",
      "yellow": "img/p/ms11-yellow.webp"
    },
    "back": null,
    "extra": []
  },
  "ms07": {
    "colors": {
      "black": "img/p/ms07-black.webp",
      "green": "img/p/ms07-green.webp",
      "white": "img/p/ms07-white.webp"
    },
    "back": null,
    "extra": []
  },
  "mt01": {
    "colors": {
      "gray": "img/p/mt01-gray.webp",
      "orange": "img/p/mt01-orange.webp",
      "red": "img/p/mt01-red.webp"
    },
    "back": null,
    "extra": []
  },
  "mp04": {
    "colors": {
      "black": "img/p/mp04-black.webp",
      "gray": "img/p/mp04-gray.webp",
      "green": "img/p/mp04-green.webp"
    },
    "back": null,
    "extra": []
  },
  "mp11": {
    "colors": {
      "blue": "img/p/mp11-blue.webp",
      "brown": "img/p/mp11-brown.webp",
      "green": "img/p/mp11-green.webp"
    },
    "back": null,
    "extra": []
  },
  "msh03": {
    "colors": {
      "black": "img/p/msh03-black.webp",
      "blue": "img/p/msh03-blue.webp",
      "green": "img/p/msh03-green.webp"
    },
    "back": null,
    "extra": []
  },
  "mj03": {
    "colors": {
      "black": "img/p/mj03-black.webp",
      "green": "img/p/mj03-green.webp",
      "red": "img/p/mj03-red.webp"
    },
    "back": "img/p/mj03-back.webp",
    "extra": []
  },
  "mj06": {
    "colors": {
      "blue": "img/p/mj06-blue.webp",
      "green": "img/p/mj06-green.webp",
      "purple": "img/p/mj06-purple.webp"
    },
    "back": "img/p/mj06-back.webp",
    "extra": []
  },
  "mj11": {
    "colors": {
      "black": "img/p/mj11-black.webp",
      "green": "img/p/mj11-green.webp",
      "red": "img/p/mj11-red.webp"
    },
    "back": "img/p/mj11-back.webp",
    "extra": []
  },
  "mh01": {
    "colors": {
      "black": "img/p/mh01-black.webp",
      "gray": "img/p/mh01-gray.webp",
      "orange": "img/p/mh01-orange.webp"
    },
    "back": null,
    "extra": []
  },
  "ws03": {
    "colors": {
      "blue": "img/p/ws03-blue.webp",
      "green": "img/p/ws03-green.webp",
      "red": "img/p/ws03-red.webp"
    },
    "back": null,
    "extra": []
  },
  "ws06": {
    "colors": {
      "gray": "img/p/ws06-gray.webp",
      "purple": "img/p/ws06-purple.webp",
      "red": "img/p/ws06-red.webp"
    },
    "back": null,
    "extra": []
  },
  "ws11": {
    "colors": {
      "green": "img/p/ws11-green.webp",
      "orange": "img/p/ws11-orange.webp",
      "yellow": "img/p/ws11-yellow.webp"
    },
    "back": null,
    "extra": []
  },
  "wh03": {
    "colors": {
      "green": "img/p/wh03-green.webp",
      "purple": "img/p/wh03-purple.webp",
      "red": "img/p/wh03-red.webp"
    },
    "back": null,
    "extra": []
  },
  "wh05": {
    "colors": {
      "orange": "img/p/wh05-orange.webp",
      "purple": "img/p/wh05-purple.webp",
      "white": "img/p/wh05-white.webp"
    },
    "back": null,
    "extra": []
  },
  "wh01": {
    "colors": {
      "green": "img/p/wh01-green.webp",
      "orange": "img/p/wh01-orange.webp",
      "purple": "img/p/wh01-purple.webp"
    },
    "back": "img/p/wh01-back.webp",
    "extra": []
  },
  "wj06": {
    "colors": {
      "blue": "img/p/wj06-blue.webp",
      "green": "img/p/wj06-green.webp",
      "purple": "img/p/wj06-purple.webp"
    },
    "back": null,
    "extra": []
  },
  "wj04": {
    "colors": {
      "orange": "img/p/wj04-orange.webp",
      "red": "img/p/wj04-red.webp",
      "white": "img/p/wj04-white.webp"
    },
    "back": null,
    "extra": []
  },
  "wp02": {
    "colors": {
      "blue": "img/p/wp02-blue.webp",
      "purple": "img/p/wp02-purple.webp",
      "red": "img/p/wp02-red.webp"
    },
    "back": "img/p/wp02-back.webp",
    "extra": []
  },
  "wp03": {
    "colors": {
      "black": "img/p/wp03-black.webp",
      "blue": "img/p/wp03-blue.webp",
      "purple": "img/p/wp03-purple.webp"
    },
    "back": null,
    "extra": []
  },
  "wsh04": {
    "colors": {
      "black": "img/p/wsh04-black.webp",
      "green": "img/p/wsh04-green.webp",
      "orange": "img/p/wsh04-orange.webp"
    },
    "back": "img/p/wsh04-back.webp",
    "extra": []
  },
  "wt02": {
    "colors": {
      "green": "img/p/wt02-green.webp",
      "orange": "img/p/wt02-orange.webp",
      "yellow": "img/p/wt02-yellow.webp"
    },
    "back": null,
    "extra": []
  },
  "wt05": {
    "colors": {
      "orange": "img/p/wt05-orange.webp",
      "purple": "img/p/wt05-purple.webp",
      "white": "img/p/wt05-white.webp"
    },
    "back": null,
    "extra": []
  },
  "mh08": {
    "colors": {
      "brown": "img/p/mh08-brown.webp",
      "purple": "img/p/mh08-purple.webp",
      "red": "img/p/mh08-red.webp"
    },
    "back": "img/p/mh08-back.webp",
    "extra": []
  },
  "mh12": {
    "colors": {
      "blue": "img/p/mh12-blue.webp",
      "green": "img/p/mh12-green.webp",
      "red": "img/p/mh12-red.webp"
    },
    "back": null,
    "extra": []
  },
  "mh05": {
    "colors": {
      "green": "img/p/mh05-green.webp",
      "red": "img/p/mh05-red.webp",
      "white": "img/p/mh05-white.webp"
    },
    "back": null,
    "extra": []
  },
  "mh11": {
    "colors": {
      "orange": "img/p/mh11-orange.webp",
      "red": "img/p/mh11-red.webp",
      "white": "img/p/mh11-white.webp"
    },
    "back": null,
    "extra": []
  },
  "mp06": {
    "colors": {
      "gray": "img/p/mp06-gray.webp",
      "green": "img/p/mp06-green.webp",
      "orange": "img/p/mp06-orange.webp"
    },
    "back": "img/p/mp06-back.webp",
    "extra": []
  },
  "mb02": {
    "colors": {
      "blue": "img/p/mb02-blue-0.webp",
      "gray": "img/p/mb02-gray-0.webp"
    },
    "back": null,
    "extra": []
  },
  "mb03": {
    "colors": {
      "black": "img/p/mb03-black-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/mb03-black-0_alt1.webp",
      "img/p/mb03-detail.webp"
    ]
  },
  "mb01": {
    "colors": {
      "blue": "img/p/mb01-blue-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/mb01-detail.webp"
    ]
  },
  "mb04": {
    "colors": {
      "black": "img/p/mb04-black-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/mb04-black-0_alt1.webp",
      "img/p/mb04-detail.webp"
    ]
  },
  "mb05": {
    "colors": {
      "black": "img/p/mb05-black-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/mb05-detail.webp"
    ]
  },
  "mb06": {
    "colors": {
      "gray": "img/p/mb06-gray-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/mb06-detail.webp"
    ]
  },
  "mg01": {
    "colors": {
      "bk": "img/p/mg01-bk-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/mg01-detail.webp"
    ]
  },
  "mg03": {
    "colors": {
      "br": "img/p/mg03-br-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/mg03-detail.webp"
    ]
  },
  "mg04": {
    "colors": {
      "bk": "img/p/mg04-bk-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/mg04-detail.webp"
    ]
  },
  "mg05": {
    "colors": {
      "br": "img/p/mg05-br-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/mg05-detail.webp"
    ]
  },
  "ug06": {
    "colors": {
      "lb": "img/p/ug06-lb-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/ug06-detail.webp"
    ]
  },
  "ug04": {
    "colors": {
      "bk": "img/p/ug04-bk-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/ug04-detail.webp"
    ]
  },
  "ug05": {
    "colors": {
      "gr": "img/p/ug05-gr-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/ug05-detail.webp"
    ]
  },
  "ug01": {
    "colors": {
      "bk": "img/p/ug01-bk-0.webp"
    },
    "back": null,
    "extra": [
      "img/p/ug01-detail.webp"
    ]
  },
  "ball": {
    "colors": {
      "ball": "img/p/luma-stability-ball-pink.webp",
      "blue": "img/p/luma-stability-ball.webp"
    },
    "back": null,
    "extra": []
  },
  "roller": {
    "colors": {
      "default": "img/p/luma-foam-roller.webp"
    },
    "back": null,
    "extra": [
      "img/p/roller-detail.webp"
    ]
  },
  "yogakit": {
    "colors": {
      "default": "img/p/luma-yoga-kit-2.webp"
    },
    "back": null,
    "extra": [
      "img/p/yogakit-detail.webp"
    ]
  },
  "strap": {
    "colors": {
      "default": "img/p/luma-yoga-strap-set.webp"
    },
    "back": null,
    "extra": [
      "img/p/strap-detail.webp"
    ]
  },
  "brick": {
    "colors": {
      "default": "img/p/luma-yoga-brick.webp"
    },
    "back": null,
    "extra": [
      "img/p/brick-detail.webp"
    ]
  },
  "shoe-knit": {
    "colors": {
      "default": "img/p/shoe-knit.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-knit-detail.webp"
    ]
  },
  "shoe-court": {
    "colors": {
      "default": "img/p/shoe-court.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-court-detail.webp"
    ]
  },
  "shoe-slipon": {
    "colors": {
      "default": "img/p/shoe-slipon.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-slipon-detail.webp"
    ]
  },
  "shoe-slides": {
    "colors": {
      "default": "img/p/shoe-slides.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-slides-detail.webp"
    ]
  },
  "shoe-boots": {
    "colors": {
      "default": "img/p/shoe-boots.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-boots-detail.webp"
    ]
  },
  "shoe-loafer": {
    "colors": {
      "default": "img/p/shoe-loafer.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-loafer-detail.webp"
    ]
  },
  "shoe-pumps": {
    "colors": {
      "default": "img/p/shoe-pumps.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-pumps-detail.webp"
    ]
  },
  "shoe-stiletto": {
    "colors": {
      "default": "img/p/shoe-stiletto.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-stiletto-detail.webp"
    ]
  },
  "shoe-sandal": {
    "colors": {
      "default": "img/p/shoe-sandal.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-sandal-detail.webp"
    ]
  },
  "shoe-flats": {
    "colors": {
      "default": "img/p/shoe-flats.webp"
    },
    "back": null,
    "extra": [
      "img/p/shoe-flats-detail.webp"
    ]
  },
  "cap-dad": {
    "colors": {
      "default": "img/p/cap-dad.webp"
    },
    "back": null,
    "extra": [
      "img/p/cap-dad-detail.webp"
    ]
  },
  "cap-beanie": {
    "colors": {
      "default": "img/p/cap-beanie.webp"
    },
    "back": null,
    "extra": [
      "img/p/cap-beanie-detail.webp"
    ]
  },
  "cap-flat": {
    "colors": {
      "default": "img/p/cap-flat.webp"
    },
    "back": null,
    "extra": [
      "img/p/cap-flat-detail.webp"
    ]
  }
}
