// End-to-end walkthrough of the core simulated journey.
// browse → search → filter → view → add to cart → voucher → checkout → demo payment → order → track → complete → history
// Usage: npm run build && npx vite preview --port 4173 & node scripts/e2e.mjs [shotsDir]
import { chromium } from 'playwright'
import fs from 'node:fs'

const BASE = process.env.BASE_URL ?? 'http://localhost:4173/'
const OUT = process.argv[2] ?? '.walkthrough/e2e'
fs.mkdirSync(OUT, { recursive: true })
const VP = process.env.VP === 'desktop' ? { width: 1366, height: 900 } : { width: 390, height: 844 }

const browser = await chromium.launch({ executablePath: process.env.CHROME ?? '/opt/pw-browsers/chromium' })
const ctx = await browser.newContext({ viewport: VP })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
page.on('console', (m) => m.type() === 'error' && !/net::|Failed to load resource/.test(m.text()) && errors.push(m.text()))

let n = 0
const shot = (name) => page.screenshot({ path: `${OUT}/${String(++n).padStart(2, '0')}-${name}.png` })
const step = (s) => console.log(`✓ ${s}`)
const go = async (r) => { await page.goto(BASE + '#' + r); await page.waitForTimeout(900) }
const expectText = async (t, timeout = 6000) => page.getByText(t).first().waitFor({ timeout })
const toastHas = async (t) => page.locator('[aria-live="polite"]').getByText(t).first().waitFor({ timeout: 5000 })

await go('/')
await page.evaluate(() => localStorage.clear())
await go('/')
await expectText('What are you craving?')
step('Home loaded (default demo user Ayesha)')

// Search
const search = page.locator('main input[aria-label="Search"]').first()
await search.fill('burger')
await expectText('See all results for “burger”')
await search.press('Enter')
await expectText('Results for “burger”')
step('Search suggestions + results page')
await shot('search')

// No-result state
await go('/search?q=qwertyzz')
await expectText('No results for “qwertyzz”')
step('Search no-result state')

// Browse + filter restaurants
await go('/food')
await expectText('restaurants')
const before = await page.getByText(/^\d+ restaurants?$/).first().innerText()
await page.getByRole('button', { name: 'Rating 4.5+' }).click()
await page.waitForTimeout(300)
const after = await page.getByText(/^\d+ restaurants?$/).first().innerText()
if (before === after) throw new Error(`Filter did not change results (${before})`)
step(`Food filter: ${before} → ${after}`)
await page.getByRole('button', { name: 'Rating 4.5+' }).click()
await go('/food?cat=burger')
await page.getByRole('link', { name: /Urban Burger BD/ }).first().click()
await expectText('Smashed patties')
step('Opened restaurant from category listing')

// Customise + add
await page.getByRole('button', { name: /The Urban Smash/ }).first().click()
await expectText('Make it a meal')
await page.getByLabel('Fries + Coke (250ml)').check()
await shot('item-modal')
await page.getByRole('button', { name: /Add to cart · ৳570/ }).click()
await toastHas('Added 1× The Urban Smash')
await page.getByRole('button', { name: 'Add Classic Fries', exact: true }).click()
await toastHas('Added Classic Fries')
step('Added customised burger (৳570) + fries')

// Cross-restaurant conflict dialog
await go('/restaurant/r-kacchi-corner')
await page.getByRole('button', { name: 'Add Jali Kabab', exact: true }).click()
await expectText('Start a new food cart?')
await page.getByRole('button', { name: 'Cancel' }).click()
step('Cross-restaurant cart conflict → cancelled')

// Cart + vouchers
await go('/cart')
await expectText('Bill details')
await page.getByPlaceholder('Enter code e.g. FOOD20').fill('FIRSTORDER')
await page.getByRole('button', { name: 'Apply', exact: true }).click()
await expectText('only valid on your first order')
await page.getByPlaceholder('Enter code e.g. FOOD20').fill('SHOP100')
await page.getByRole('button', { name: 'Apply', exact: true }).click()
await expectText('only valid on shopping orders')
await page.getByPlaceholder('Enter code e.g. FOOD20').fill('FOOD20')
await page.getByRole('button', { name: 'Apply', exact: true }).click()
await expectText('You save ৳')
step('Voucher validation (first-order, scope) + FOOD20 applied')
await shot('cart')
await page.getByRole('button', { name: /Proceed to checkout/ }).click()

// Checkout
await expectText('Where should we (not) deliver?')
const cont = () => page.getByRole('button', { name: /Continue to/ }).last().click()
await cont()
await expectText('Delivery method')
await page.getByText('Priority delivery').click()
await cont()
await expectText('Payment method')
await page.getByRole('button', { name: /Credit \/ Debit card/ }).click()
await page.getByRole('button', { name: 'New test card' }).click()
await page.getByPlaceholder('4242 4242 4242 4242').fill('4111111111111111')
await cont()
await expectText('Use a demo test card')
step('Real-looking card number rejected')
await page.getByPlaceholder('4242 4242 4242 4242').fill('4000000000000002')
await page.getByPlaceholder('TEST USER').fill('Test User')
await page.getByPlaceholder('12/29').fill('1229')
await page.getByPlaceholder('123').fill('123')
await cont()
await expectText('Review your test order')
await page.getByText('I understand this is a').click()
await shot('review')
await page.getByRole('button', { name: /Place test order/ }).last().click()
await expectText('Verification code (OTP)')
await page.getByPlaceholder('••••••').fill('123456')
await page.getByRole('button', { name: 'Verify' }).click()
await expectText('Payment failed', 8000)
step('Declined test card → simulated failure')
await shot('payment-failed')
await page.getByRole('button', { name: 'Change method' }).click()
await expectText('Payment method')
await page.getByRole('button', { name: /^bK bKash/ }).click()
await cont()
await page.getByRole('button', { name: /Place test order/ }).last().click()
await page.getByPlaceholder('01700000000').fill('01712345678')
await page.getByRole('button', { name: 'Continue' }).click()
await expectText('Only demo wallet numbers are accepted')
step('Real-looking wallet number rejected')
await page.getByPlaceholder('01700000000').fill('01700000000')
await page.getByRole('button', { name: 'Continue' }).click()
await page.getByPlaceholder('••••••').fill('123456')
await page.getByRole('button', { name: 'Verify' }).click()
await page.getByPlaceholder('•••••').fill('12345')
await shot('bkash-pin')
await page.getByRole('button', { name: /Confirm payment/ }).click()
await expectText('Test order placed!', 10000)
const orderId = (await page.locator('h1').first().innerText()).replace('Order #', '').trim()
step(`bKash demo payment succeeded → ${orderId} placed`)
await shot('order-placed')

// Tracking → completion
await expectText('Order Confirmed')
await page.getByRole('button', { name: '60×' }).click()
for (let i = 0; i < 4; i++) {
  await page.getByRole('button', { name: /Skip to next stage/ }).click()
  await page.waitForTimeout(400)
  if (i === 2) await shot('tracking-on-the-way')
}
await expectText('Simulation Complete')
await expectText('No real product was delivered.')
step('Order progressed through all stages → Simulation Complete')
await page.getByRole('button', { name: '2 star' }).first().click()
await shot('delivered')

// History + reorder
await go('/orders')
await page.getByRole('tab', { name: /Delivered/ }).click()
await expectText(orderId)
step('Order appears in history')
await page.getByRole('button', { name: 'Reorder' }).first().click()
await expectText('Your cart')
step('Reorder → cart')

// Shopping flow
await go('/shop?cat=shoes')
await expectText('Shoes')
await page.getByRole('link', { name: /AirFlow Knit Runner/ }).first().click()
await expectText('About this product')
await page.getByRole('button', { name: 'Add to cart', exact: true }).click()
await expectText('Please select a size')
await page.getByRole('button', { name: '42', exact: true }).click()
await page.getByRole('button', { name: 'Teal' }).click()
await page.getByRole('button', { name: 'Add to cart', exact: true }).click()
await toastHas('Added to cart')
step('Product: size validation, colour + size picked, added')
await shot('product')
await go('/cart?tab=shop')
await page.getByPlaceholder('Enter code e.g. FOOD20').fill('SHOP100')
await page.getByRole('button', { name: 'Apply', exact: true }).click()
await expectText('You save ৳100')
await page.getByRole('button', { name: /Proceed to checkout/ }).click()
await cont(); await cont()
await page.getByRole('button', { name: /Cash on delivery/ }).click()
await cont()
await page.getByText('I understand this is a').click()
await page.getByRole('button', { name: /Place test order/ }).last().click()
await expectText('Test order placed!', 10000)
await expectText('Parcel delivery')
step('Shopping checkout with COD + SHOP100 → parcel tracking')

// Notifications, support, admin
await go('/notifications')
await expectText('Order Confirmed')
step('Notifications list order updates')
await go('/help/chat')
await page.getByRole('button', { name: 'Where is my order?' }).click()
await expectText('Estimated arrival', 8000)
step('Support chat answered order status')
await go('/admin/vouchers')
await page.getByRole('button', { name: 'Create voucher' }).first().click()
await page.getByPlaceholder('CRAVE25').fill('E2ETEST')
await page.getByRole('button', { name: 'Create voucher' }).last().click()
await toastHas('Voucher E2ETEST created')
await go('/admin/orders')
await page.getByRole('button', { name: 'Create demo order' }).first().click()
await page.getByRole('button', { name: 'Create order' }).click()
await toastHas('Created DK-')
step('Admin: voucher + demo order created')

// Logout → new user signup → FIRSTORDER eligible
await go('/account')
await page.getByRole('button', { name: 'Log out' }).click()
await page.getByRole('button', { name: 'Log out' }).last().click()
await go('/login')
await page.getByPlaceholder('1712-345678').fill('01999888777')
await page.getByRole('button', { name: 'Send code' }).click()
await page.getByPlaceholder('••••••').fill('123456')
await page.getByRole('button', { name: 'Verify' }).click()
await page.getByPlaceholder('Your name').fill('Rahim Uddin')
await page.getByRole('button', { name: 'Create demo account' }).click()
await expectText('What are you craving?')
step('Logout → OTP signup as new user')

await browser.close()
if (errors.length) {
  console.log('\nConsole/page errors:\n' + errors.join('\n'))
  process.exit(1)
}
console.log('\nE2E walkthrough passed with no console errors.')
